### ISSUE TITLE
insert_dns_preftech not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#964] opened 2015-04-06 16:01 UTC
```
What steps will reproduce the problem?
1.Enable the "ModPagespeedEnableFilters insert_dns_prefetch"

What is the expected output? What do you see instead?
From the example on pagespeed docs here 
(https://developers.google.com/speed/docs/mod_pagespeed/filter-insert-dns-prefet
ch), I didn't find any line belongs to that filter. (eg. <link 
rel="dns-prefetch" href="//www.gravatar.com">)

The URL http://www.gravatar.com is exist on my page.

What version of the product are you using (please check X-Mod-Pagespeed
header)?
mod-pagespeed-stable-1.7.30.5-r3847

On what operating system?
ubuntu 12.04 LTS
Which version of Apache?
Apache/2.2.22 
Which MPM?
No idea
URL of broken page:I've attched the file where i need to check and also the 
pagespeed.conf file. I can be sure that pagespeed is working. As the images are 
getting loaded lazily. but is there any means where i can test 
insert_dns_prefetch?



```

Original issue reported on code.google.com by `nairakhi...@gmail.com` on 30 Jul 2014 at 2:33

Attachments:
- [dummy.html](https://storage.googleapis.com/google-code-attachments/modpagespeed/issue-964/comment-0/dummy.html)
- [pagespeed.conf](https://storage.googleapis.com/google-code-attachments/modpagespeed/issue-964/comment-0/pagespeed.conf)

**Comment by jmarantz** [comment] 2018-09-28 14:46
I think this filter is working as well as it can given the design tradeoffs that mod_pagespeed has made from the beginning, which is to prioritize fast delivery of HTML over completing optimizations.

The issue is that the dns prefetch tag has value only in the beginning of the page, and only then if the page doesn't get delivered to the browser all at once, but is streamed out slowly (e.g. some content pulled from a slow database or similar).  In that scenario, the early DNS prefetch can get the browser doing something useful while waiting for the rest of the page.

The problem is that mod_pagespeed doesn't know what needs to be prefetched until *it* can see the whole page. So it solves the problem with its *property cache*. The property cache caches observed properties of an HTML page from when it was served earlier. There is no perfect way for mod_pagespeed to know how long to keep entries in the property cache. At some point the page can change and the domains that were previously important may change.

So mod_pagespeed periodically refreshes this cache in response to page requests, and arbitrarily only considers data less than 5 minutes old to be valid. This should in practice be effective on pages that are frequently viewed. However, on new pages, or debug versions of sites that are essentially never accessed, the property cache will be stale, and DNS prefetch will not work on the first view of a page. But if you reload the page it will work. 

Thus this feature is useful for accelerating pages that are visited more than once every 5 minutes.

**Comment by jmarantz** [comment] 2018-09-28 14:51
I just tried refreshing https://www.modpagespeed.com/examples/insert_dns_prefetch.html?PageSpeed=on&PageSpeedFilters=insert_dns_prefetch a couple of times and the expected DNS prefetch links got inserted:
```
<link rel="dns-prefetch" href="//www.gstatic.com">
<link rel="dns-prefetch" href="//ajax.googleapis.com">
```

So closing this issue for now.

**Closed as completed by jmarantz** 2018-09-28 14:51 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
