### ISSUE TITLE
Bootstrap background data:image/svg+xml issue

### ISSUE THREAD

**Issue by seb-witt** [apache/incubator-pagespeed-mod#1901] opened 2019-06-20 19:42 UTC
Hey everyone. Im having an issue with an background image svg from bootsrap

Im using pagespeed 1.13.35.2-0

Pagespeed seem to incorrectly, convert, optimize or whatever ( i'm not sure at this point ) this particular image. All else is fine everywhere

This is the rule in question
`.navbar-dark .navbar-toggler-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 0.5);
}`

And pagespeed makes the following out of it, which doesn't seem to be valid. It not appears in the network request list either
`.navbar-dark .navbar-toggler-icon {
    background-image: url(data:image/svg+xml;charset=utf8;base64,PHN2Z1wgdmlld0JveD1cJzBcIDBcIDMwXCAzMFwnXCB4bWxucz1cJ2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCc+PHBhdGhcIHN0cm9rZT1cJ3JnYmFcKDI1NSxcIDI1NSxcIDI1NSxcIDAuNVwpXCdcIHN0cm9rZS13aWR0aD1cJzJcJ1wgc3Ryb2tlLWxpbmVjYXA9XCdyb3VuZFwnXCBzdHJva2UtbWl0ZXJsaW1pdD1cJzEwXCdcIGQ9XCdNNFwgN2gyMk00XCAxNWgyMk00XCAyM2gyMlwnLz48L3N2Zz4=);
}`

Is this an known issue? I couldnt find anything related in the docs, beside inline_images filter ( which i need )
Is there some way to prevent the converting just for this one thing?

Thank you

**Comment by oschaaf** [comment] 2019-06-20 21:38
That looks like a bug to me, haven't seen it reported earlier. Do you have a live example to share?

**Comment by seb-witt** [comment] 2019-06-21 08:15
Yes, you can see it live on  https://minecraft-server.net/
You need to resize your window to <991 px to see it broken

Thank you

**Comment by oschaaf** [comment] 2019-06-21 09:05
I haven't attempted a root cause analysis, but can you try turning off `combine_css` to see if that resolves the problem?

**Comment by seb-witt** [comment] 2019-06-21 12:35
I'll have a look later today and will let you know

**Comment by seb-witt** [comment] 2019-06-21 14:43
https://minecraft-server.net/?PageSpeed=on&PageSpeedFilters=-combine_css
combine_css filter is at fault as you guessed

**Comment by oschaaf** [comment] 2019-06-21 22:33
I suspected that a script was breaking on the url changes made by the css combining. While I'm not 100% sure, disabling the combiner seems to back that hypothesis. Closing this.

**Closed as completed by oschaaf** 2019-06-21 22:33 UTC

**Comment by seb-witt** [comment] 2019-06-22 09:51
And what can be done? Any eta on when this will be fixed?

**Comment by oschaaf** [comment] 2019-06-22 10:57
I do not think that this is actionable in this project. Sites that have scripts depending on resource urls staying the same effectively block some automatic optimization opportunities. Maybe we could detect these breakages and automatically back out offending optimizations, but I think that is a significant effort and no one is working on it as far as I know. But OptimizeForBandwith mode is available today, and can be used by sites prone to breakage caused by  resource url changes

**Comment by seb-witt** [comment] 2019-06-22 13:12
I see, makes sense. Easy solution, i just replaced the background svg with an fontawesome icon, looking almost the same. Works out ok i guess if you use fontawesome on your website.

Thanks for your time and this amazing project!
