### ISSUE TITLE
Having "max-age=300,private" in a css file

### ISSUE THREAD

**Issue by bnegrao** [apache/incubator-pagespeed-mod#1659] opened 2017-10-30 20:31 UTC
Hi, the css file from the URL bellow is returning with "Cache-Control:max-age=300,private", why?

    https://ogcss.infoglobo.com.br/9876543210/css/A.main.css.pagespeed.cf.eJTHJwiwVY.css

We use few filters:

    ModPagespeedEnableFilters extend_cache
    ModPagespeedEnableFilters rewrite_css
    ModPagespeedEnableFilters fallback_rewrite_css_urls
    ModPagespeedEnableFilters trim_urls
    ModPagespeedEnableFilters rewrite_style_attributes_with_url
    ModPagespeedEnableFilters insert_dns_prefetch
    ModPagespeedEnableFilters collapse_whitespace
    ModPagespeedEnableFilters remove_comments
    ModPagespeedEnableFilters remove_quotes
    ModPagespeedEnableFilters convert_meta_tags
    ModPagespeedEnableFilters move_css_to_head
    ModPagespeedEnableFilters resize_images
    ModPagespeedEnableFilters convert_gif_to_png
    ModPagespeedEnableFilters convert_png_to_jpeg
    ModPagespeedEnableFilters recompress_png
    ModPagespeedEnableFilters recompress_jpeg

My pagespeed is mod-pagespeed-stable-1.11.33.4-0.x86_64

Even if I modify that css file on disk, pagespeed updates the URL with a new hash,  but the cache control header continues as max-age=300,private even in the new URL.

We don't see that happening with other css files. The issue does not happen in our staging environment, it only happens in production.

**Comment by oschaaf** [comment] 2017-10-30 20:50
Are there any url references to images/css in the css response that do not exist (respond with a 404)?
What happens if you clear mod_pagespeed's caches? Does the problem go away?
https://www.modpagespeed.com/doc/system#purge_cache

**Comment by bnegrao** [comment] 2017-10-30 21:11
I just verified that all the image URLs respond with HTTP 200.

I have 4 apache servers using a memcached cache. I purged the cache by using the "purge entire cache" button in each apache server, but the problem persists.

I didn't try to restart the apache servers or the memcached servers.

**Comment by oschaaf** [comment] 2017-10-30 21:39
One thing that strikes me is that the html is served with:
```
Cache-control:max-age=180
```

mod_pagespeed doesn't serve html like that out of the box. Do you have the downstream caching feature enabled? 
If not, you may have to be careful combining caching html with user-agent specific optimizations like webp conversion.

I think this could be related to what you observe: there is a hash in the `.pagespeed.` url (`eJTHJwiwVY`). If the hash mismatches with what the module figures it should be for the user-agent performing the request, the response it comes up with would also be served with ` Cache-Control:max-age=300,private`.

**Comment by bnegrao** [comment] 2017-10-30 21:52
We don't have the downstream caching enabled. We have cache servers in front of pagespeed.

We don't have the webp filters enabled. The image filters are:

    ModPagespeedEnableFilters resize_images
    ModPagespeedEnableFilters convert_gif_to_png
    ModPagespeedEnableFilters convert_png_to_jpeg
    ModPagespeedEnableFilters recompress_png
    ModPagespeedEnableFilters recompress_jpeg

Very weird is that the "show_metadata" admin tool never finds that url (https://ogcss.infoglobo.com.br/9876543210/css/A.main.css.pagespeed.cf.eJTHJwiwVY.css) in the cache! Why?

**Comment by bnegrao** [comment] 2017-10-30 21:58
That css URL is present in our homepage https://oglobo.globo.com/.

You mentioned that it could be something related to the user agent and some problem with downstream caching. But I don't think so.

 If I request the homepage directly in the apache server using curl to localhost, the same css URL is shown in the html:

    <link rel=stylesheet type="text/css" href="https://ogcss.infoglobo.com.br/9876543210/css/A.main.css.pagespeed.cf.eJTHJwiwVY.css"/>

If the user agent could affect the URL, the curl request should have seen a different URL.

**Comment by oschaaf** [comment] 2017-10-31 09:42
Sounds like we can rule that out. It does seem that the domain of the css changes, and that vaguely rings a bell of an earlier report with similar trouble. Let me see if I can find that.

**Comment by oschaaf** [comment] 2017-10-31 09:44
Yes, there was https://github.com/pagespeed/ngx_pagespeed/issues/1321 but unfortunately it doesn't help us any further here.
To see if domain rewriting is related to the symptom, would it be possible for you to: temporarily switch the domain rewriting off, purge the module's caches, and see if what the cache-control header looks like subsequently?

**Comment by oschaaf** [comment] 2017-10-31 09:50
There was also https://github.com/pagespeed/mod_pagespeed/issues/1080 -- I see you posted there earlier, sorry for missing that.

**Comment by jmarantz** [comment] 2017-10-31 12:23
I just took a look at /
https://ogcss.infoglobo.com.br/9876543210/css/main.css and the rewirtten
version
https://ogcss.infoglobo.com.br/9876543210/css/A.main.css.pagespeed.cf.eJTHJwiwVY.css

I noticed in the original main.css, you have a lot of references to URLs
like:*../img/bt_boxp.png*
which then got optimized to
*/9876543210/img/xbt_boxp.png.pagespeed.ic.ctr8WYalzP.png*

The relative URLs could be an issue in some server setups. The way this can
show up is that PageSpeed's view of how that CSS file should be interpreted
when it is parsing HTML is different from how it interprets the file when
requested directly from a browser.  E.g. is there any hostname mapping that
occurs within your network?

I'm wondering what the significance of the "9876543210" is. Does that
prefix change over time?

Also as noted earlier in #1080
<https://github.com/pagespeed/mod_pagespeed/issues/1080>, any proxy-cache
in between your pagespeed servers and clients could cause some issues, e.g.
by altering or removing User-Agent or Accept headers.  You are not enabling
webp, but there may be other user-agent sensitivities that I can't think of
offhand right now.  E.g. fonts.

It is curious that all your other CSS files referenced from
https://oglobo.globo.com/ has a one year cache lifetime.  But a twist that
I don't understand is that some of them have explicit "public" in the
cache-control and some don't.  I think that PageSpeed just passes that
through.

One last question on versioning.   You said you use
mod-pagespeed-stable-1.11.33.4-0.x86_64.  You know that 1.12 is stable now,
right?  Any reason not to upgrade?  Also, are you sure that all your
servers with mod_pagespeed enabled are running the same version?

In the meantime, if you want to just work around this, just use
   ModPagespeedDisallow */main.css
to exclude that one file.  It is already minified at oriign

-Josh

**Comment by bnegrao** [comment] 2017-10-31 16:04
Jmarantz,

> The relative URLs could be an issue in some server setups. The way this can
> show up is that PageSpeed's view of how that CSS file should be interpreted
> when it is parsing HTML is different from how it interprets the file when
> requested directly from a browser.  E.g. is there any hostname mapping that
> occurs within your network?

Since Pagespeed is being able to fetch and process each image file mentioned in the css I wouldn't worry with hostname mappings... If there was a problem on that area pagespeed would fail to fetch the files, right?

> I'm wondering what the significance of the "9876543210" is. Does that
> prefix change over time?

That was our mechanism to renew the browser caches before we used pagespeed. Now that we're using pagespeed that number does not change anymore, but it is still there if we ever need to change it again.

> Also as noted earlier in #1080
> <#1080>, any proxy-cache
> in between your pagespeed servers and clients could cause some issues, e.g.
> by altering or removing User-Agent or Accept headers

We do change the "Accept-Encoding" header when it passes through our varnish servers. The algorithm is bellow. 

    #lets reduce the compression algorithms so we do not have different object in cache
    if (req.http.Accept-Encoding) {
        if (req.url ~ "(?i)\.(jpg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {
            # No point in compressing these
            unset req.http.Accept-Encoding;
        } elsif (req.http.Accept-Encoding ~ "gzip") {
            set req.http.Accept-Encoding = "gzip";
        } elsif (req.http.Accept-Encoding ~ "deflate") {
            set req.http.Accept-Encoding = "deflate";
        } else {
            # unkown algorithm
            unset req.http.Accept-Encoding;
        }
    }

In the last "else" clause we can unset the Accept-Encoding header.

But if I don't think that missing headers are the issue because, as I mentioned in [this comment](https://github.com/pagespeed/mod_pagespeed/issues/1659#issuecomment-340597487) the css url does not change when I fetch the page locally in the apache server using curl... 

> I don't understand is that some of them have explicit "public" in the
> cache-control and some don't. 

Me neither! that's weird.

> One last question on versioning.   You said you use
> mod-pagespeed-stable-1.11.33.4-0.x86_64.  You know that 1.12 is stable now,
> right?  

No we didn't! We'll manage to upgrade it soon.

> are  you sure that all your servers with mod_pagespeed enabled are running the same version?

Yes, I just verified that.

**Comment by bnegrao** [comment] 2017-10-31 20:30
Can you explain to me why I can never see the url https://ogcss.infoglobo.com.br/9876543210/css/A.main.css.pagespeed.cf.eJTHJwiwVY.css with the **/pagespeed_global_admin/cache#show_metadata** tool? 

The tool only shows:

    Metadata cache key:rname/cf_J2XEpcBeiLH4k-DFPiCT/https://ogcss.infoglobo.com.br/9876543210/css/main.css@A.@.A_
    cache_ok:false
    can_revalidate:false
    partitions:


Does that have to do with the max-age=300 symptom?

**Comment by jmarantz** [comment] 2017-10-31 20:52
Yeah I think that's exactly right.  Somehow PageSpeed thinks that the content hash for the optimized main.css is not `eJTHJwiwVY ` but is something else.  So it doesn't find the cache entry.

The thinking behind serving it with cc private/300 is that the content must be in the process of being updated, so we'd rather serve stale content than 404, but we don't want to serve the stale content to too many users (hence 404) or for very long (hence 300 seconds).

But because this is a CSS file that references lots of images, a single byte of difference in the images between the servers can cause the image's md5 sum to be different, and therefore cause the CSS md5 sum to be different.

I've also noticed that your CSS file has some inlined image data as well, which is a feature that I thought mod_pagespeed disabled by default.  However, it looks like there are some base64 images even in your origin main.css.  I wonder if that's related (pure speculation).

**Comment by bzica** [comment] 2017-11-06 16:48
After the upgrade to version 1.12 the problem is solved!! Thank you guys.

you can close this issue.

**Closed as completed** 2017-11-06 17:27 UTC
