### ISSUE TITLE
PageSpeed URL control wildcards don't work properly

### ISSUE THREAD

**Issue by crowell** [apache/incubator-pagespeed-mod#1294] opened 2016-04-26 15:30 UTC
In one level of `.htaccess` specify `ModPagespeedDisallow *` and in a higher level specify `ModPagespeedAllow *example.com*`, example.com will still be shown as disallowed.

**Comment by jmarantz** [comment] 2016-04-26 15:33
If I understand your description, this is working as intended.

E.g.
`htdocs/foo/.htaccess :         ModPagespeedAllow *example.com*`
`htdocs/foo/bar/.htaccess :   ModPagespeedDisallow *`

Any time a file in foo/bar/ is referenced, the Disallow \* will override the .htaccess in foo/

**Comment by crowell** [comment] 2016-04-26 15:55
@jmarantz no, the opposite, the disallow in the root, and then the allow in
/foo/.htaccess

**Comment by jeffkaufman** [comment] 2016-06-28 12:56
@jmarantz I'm having trouble understanding  07c1fcc: is it that you thought this might have been a bug in `MergeOptions`, and you created a unit test to elicit the bug, but the unit test passed?

**Comment by jeffkaufman** [comment] 2016-06-28 13:02
Reproduced:

```
mod_pagespeed_test/
  issue1294/
    .htaccess: ModPagespeedDisallow *
    subdir/
      .htaccess: ModPagespeedAllow *foo*
      foo.js: document.write("hello ");
      bar.js: document.write("world");
      index.html: <script src=foo.js></script><script src=bar.js></script>

$ curl localhost:8080/mod_pagespeed_test/issue1294/subdir/
<script src="foo.js"></script>
<script src="bar.js"></script>
```

**Comment by jeffkaufman** [comment] 2016-06-28 13:07
When reversing the two `.htaccess` files we still don't see `foo.js` get rewritten, so it's not just handling them backwards or something.

**Comment by hillsp** [comment] 2016-06-30 18:35
I cannot reproduce this using what Josh checked in above; `ModPagespeedAllow *purple*` still works just fine. If I comment out the entire Allow in the override dir, the test fails.

**Comment by jeffkaufman** [comment] 2016-06-30 18:54
The test @hillsp was referring to as "what Josh checked in above" was https://github.com/pagespeed/mod_pagespeed/commit/4d3acd9cd3c5b9a573da9b0627da6475d3feb97b plus https://github.com/pagespeed/mod_pagespeed/commit/6b0cd0c3aae30a7cd733d7e0196446e52944bd8c

**Comment by jeffkaufman** [comment] 2016-06-30 18:55
Hypothesis is that `.htaccess` merging works correctly in the ipro flow but not the html flow.

**Comment by hillsp** [comment] 2016-07-07 17:32
Turns out that this is a problem with FastWildcardGroup and isn't related to the merging at all. @jmaessen has a fix.

**Closed as completed** 2016-07-08 18:30 UTC
