### ISSUE TITLE
DownStream SSI Problem

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1754] opened 2018-03-01 10:49 UTC
i setup downstream cache with varnish 5, followed this guide 
https://www.modpagespeed.com/doc/downstream-caching
i think working well but ssi stopped working.
i can see comments this 
`<!--# include virtual="/ssi.php?block_id=42&ttl=60m" -->`
varnish running port 6081
ngninx running port 80 proxy passed to 6081

how can i fix this ?

pls help

**Comment by oschaaf** [comment] 2018-03-02 15:30
Closing this as a duplicate of https://github.com/apache/incubator-pagespeed-ngx/issues/1541

**Closed as completed by oschaaf** 2018-03-02 15:30 UTC
Labels: duplicate
