### ISSUE TITLE
recompress_images filter breaks Firefox on Android

### ISSUE THREAD

**Issue by geotekberlin** [apache/incubator-pagespeed-mod#1160] opened 2015-10-27 11:32 UTC
"recompress_images" breaks jpg images on Firefox mobile. The optimized Images show up as empty boxes with the correct size and Alt text only. All other browsers that I tested (Firefox on Windows, Chrome, IE11) are rendering the optimized images correctly

It is interesting that disabling recompress_jpeg is not enough to work around the bug, I have to disable recompress_images or rewrite_images altogether in order to work around the bug.

Website involved: http://geotek.de/
(recompress_images is disabled at the moment, but I can enable it any time if someone would like to see the bug)

Client Versions:
Firefox mobile 41.0.2
Android 5.0.1

Server Versions:
mod_pagespeed-1.9.32.4-4.1.x86_64 (Prebuilt Suse Package)
OpenSuse 13.2 x64
Apache 2.4.10-25.1

Pagespeed configuration is default out of the box, nothing changed or altered

**Comment by crowell** [comment] 2015-10-27 13:54
I just tested on firefox for android v41.0.2, turning on the recompress_images filters with query options

[http://geotek.de/cms/?PageSpeedFilters=+debug,+recompress_images](http://geotek.de/cms/?PageSpeedFilters=+debug,+recompress_images)

```

mod_pagespeed on
Filters:
ah  Add Head
cc  Combine Css
jc  Combine Javascript
gp  Convert Gif to Png
jp  Convert Jpeg to Progressive
jw  Convert Jpeg To Webp
mc  Convert Meta Tags
pj  Convert Png to Jpeg
db  Debug
ec  Cache Extend Css
ei  Cache Extend Images
es  Cache Extend Scripts
fc  Fallback Rewrite Css 
if  Flatten CSS Imports
hw  Flushes html
ci  Inline Css
ii  Inline Images
il  Inline @import to Link
ji  Inline Javascript
js  Jpeg Subsampling
rj  Recompress Jpeg
rp  Recompress Png
rw  Recompress Webp
ri  Resize Images
cf  Rewrite Css
jm  Rewrite External Javascript
jj  Rewrite Inline Javascript
cu  Rewrite Style Attributes With Url
cp  Strip Image Color Profiles
md  Strip Image Meta Data

Options:
EnableRewriting (e) 1
FileCacheInodeLimit (afcl) 500000
RunExperiment (fur) False
Statistics (ase) True
StatisticsLogging (asle) True

#NumFlushes            0
#EndDocument after     9754us
#Total Parse duration  1060us
#Total Render duration 16979us
#Total Idle duration   8694us
No critical images detected.
The following filters were disabled for this request:
    SupportNoscript
```

And the images appear normally.

Did you change anything else in the configuration between now and then?

**Comment by geotekberlin** [comment] 2015-10-27 15:02
Hi Jeffrey,

yes, I had the option ModPagespeedDisableFilters recompress_images set.
I took out this option and the images are gone again on my smarphone.

Martin

**Comment by geotekberlin** [comment] 2015-10-30 11:42
I can't afford to leave the production site on with missing images any longer, so I had to disable recompress_images again.

The broken images can now be viewed on http://staging.geotek.de/cms/

Any ideas what's going wrong?

@Jeffrey: Please delete the image above, it is licensed material from a stock photo agency that is known to enforce copyright violations very rigorously, I don't want you to get into trouble!

**Comment by crowell** [comment] 2015-10-30 20:11
@geotekberlin it seems like we're serving .webp files to firefox mobile, which cant read .webp.
these should only be served to android/chrome browsers.

**Comment by crowell** [comment] 2015-10-30 20:12
this is most likely a bug on our side, do you have any sort of caching in place in front of apache that could cause the pages to not be handled by apache, and instead just from the caching layer?

**Comment by geotekberlin** [comment] 2015-10-30 23:01
The cms system does some php based caching and css combining but there is no cache and no proxy in front of apache. 

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Jeffrey Crowell notifications@github.com 
Datum: 30.10.2015  21:12  (GMT+01:00) 
An: pagespeed/mod_pagespeed mod_pagespeed@noreply.github.com 
Cc: geotekberlin ka@geotek.de 
Betreff: Re: [mod_pagespeed] recompress_images filter breaks Firefox on
  Android (#1160) 

this is most likely a bug on our side, do you have any sort of caching in place in front of apache that could cause the pages to not be handled by apache, and instead just from the caching layer?

**Comment by jeffkaufman** [comment] 2015-11-13 15:09
@huibaolin You were working on this, right?  Is the problem that we see "android" in the UA and think "android browser" and so send WebP?

**Comment by huibaolin** [comment] 2015-11-13 15:40
Yes. I've a fix for this bug and the fix has been approved.

And yes, the problem is caused by the "Android" substring in the UA, so it is confused as Android browser, and so we send WebP to it.

**Comment by jeffkaufman** [comment] 2015-11-13 19:38
Ok, thanks.  Let me know when the fix is in?

**Comment by crowell** [comment] 2015-11-25 14:42
closed by https://github.com/pagespeed/mod_pagespeed/commit/1ad70a54c1410bb459f070194ed7b6275854e71f will be included in the next beta release.

**Comment by crowell** [comment] 2015-11-25 14:43
closed by https://github.com/pagespeed/mod_pagespeed/commit/41871f9e0ac97a177dd188b40c8e48c991e4f575 will be included in the next beta release.

**Closed as completed by crowell** 2015-11-25 14:42 UTC
