### ISSUE TITLE
java script break

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1058] opened 2015-04-06 16:04 UTC
```
What steps will reproduce the problem?
1.modspeed on the javascript not loaded.
2.When the more number of user visit the site the scripts are collapse
3.

What is the expected output? What do you see instead?
How to overcome ?

What version of the product are you using (please check X-Mod-Pagespeed
header)?

On what operating system?

Which version of Apache?
2.0
Which MPM?

URL of broken page:



```

Original issue reported on code.google.com by `rajaram....@samrantech.com` on 25 Mar 2015 at 10:44

**Comment by crowell** [comment] 2015-04-10 15:25
duplicate of #1059

**Closed as completed by crowell** 2015-04-10 15:25 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
