### ISSUE TITLE
issue when upgrates version from 1.2.24.1-2581 to 1.8.31.5-4311

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1035] opened 2015-04-06 16:04 UTC
```
Hi, i'm working with Apache 2.2 and i just tried to upgread my pagespeed 
version from 1.2.24.1-2581 to 1.8.31.5-4311.

My issue is when a do an Ajax call, and at the response i resive my expected 
HTML but with a tag added <head />.

This is strage, because with the old version, everithing works fine, but with 
the new one, only works if i don't use the filters related like, add_head, 
move_css_to_head, combine_heads.

I don't know if the problem is related with the module_headers that i'm using 
and may not compatible with this version of pagespeed.

Any help would be nice

Thanks

Marco

```

Original issue reported on code.google.com by `marcov...@gmail.com` on 15 Dec 2014 at 1:14

**Comment by jeffkaufman** [comment] 2015-05-05 14:53
Duplicate of #1034

**Closed as completed by jeffkaufman** 2015-05-05 14:53 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
