### ISSUE TITLE
Add directive to allow MPS rewrite of 404 pages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#280] opened 2015-04-06 15:40 UTC
```
Some users have functional content on 404 pages and would prefer them to be 
rewritten.

While we've had some trouble in this area in the past, it's likely that other 
safeguards, like not trying to refetch a failed resource for 5 minutes, may 
eliminate the possibility of a death spiral.

But, to be on the safe side, we could have this enabled with a user directive 
in the pagespeed.conf file.

```

Original issue reported on code.google.com by `jmara...@google.com` on 2 May 2011 at 5:27

**Comment by jeffkaufman** [comment] 2016-01-21 16:32
Got another request for this today on the mailing list: https://groups.google.com/d/msgid/mod-pagespeed-discuss/341b4a04-62b7-44d1-9bca-3f511abfeee4%40googlegroups.com

**Comment by morlovich** [comment] 2016-01-21 18:32
Note that the way we install our filter won't work with this in Apache 2.4, if I recall correctly.

**Comment by qwerty4030** [comment] 2016-01-25 21:06
#170 was reopened for a similar request: https://groups.google.com/forum/#!topic/mod-pagespeed-discuss/2TReQ10j9Sk

**Comment by jeffkaufman** [comment] 2016-02-02 15:11
Closing this as a duplicate of #170; follow that for updates.

Thanks @qwerty4030

**Closed as completed by jeffkaufman** 2016-02-02 15:11 UTC
Labels: Priority-Medium, auto-migrated, Type-Enhancement
