### ISSUE TITLE
CSS files & Images are broken

### ISSUE THREAD

**Issue by balajikaliamoorthy** [apache/incubator-pagespeed-mod#1633] opened 2017-09-18 14:22 UTC
Hello,
After installed pagespeed module in our site, CSS and Image names were changed and all the requests are blocked and its went to 404 not found.

BROWSER CONSOLE:

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://************/A.globalmincss.css+globalcss,,_css,,_themes,,_az-theme.css+overrides,,_css,,_**### override-uk.css,Mcc.hV8uP1bquO.css.pagespeed.cf.6Le1YYIVs0.css**

in Apache log:
:WARNING:resource_fetch.cc(195)] Fetch failed for resource url 
******152x152.png.pagespeed.ic.LP9mYviP83.png, status=404
Failed to delete file /var/log/pagespeed/stats_log_global: Permission denied

Seems css, js and images's actual paths were changes and its causing the issue. 

which filter needs to disable to fix this issue?

Thanks

**Comment by Lofesa** [comment] 2017-09-20 19:01
Hi balajikaliamoorthy
Seems like you don´t have a *.pagespeed.* file handler. These files are stored in the pagespeed cache. I don´t know if in Apache you need something like in Nginx. In nginx you need a location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
  add_header "" "";
}
the directive is like a diectory directive in apache.....
can you post your pagespeed conf here?

**Comment by balajikaliamoorthy** [comment] 2017-09-21 07:37
HI Lofesa,

Please find below the configuration which we have added in the **VHOST** file?
Modpagespeed off
ModPagespeedEnableFilters collapse_whitespace

Only this 2 lines only we have added.

**Please let us know if we need to change any permission for the log path?**



[pagespeed.txt](https://github.com/pagespeed/mod_pagespeed/files/1320308/pagespeed.txt)
[httpd-pagespeed.txt](https://github.com/pagespeed/mod_pagespeed/files/1320310/httpd-pagespeed.txt)

**Comment by Lofesa** [comment] 2017-09-21 08:25
Hi
For the log path, the user that run the httpd process (apache?) must have r/w permision or better be the owner.
To have acces to the log info, you need to set a handler for each one like this:
```
<Location /PATH>
   Order allow,deny
   Allow from localhost
   Allow from 127.0.0.1 (or whatever ip you grant access to the stats)
   SetHandler HANDLER_NAME
</Location>
```
as stated [here](https://www.modpagespeed.com/doc/admin).

Whit the Modpagespeed off directive you have Modpagespeed disabled, you need to put it on to pagespeed work

The path ModPagespeedFileCachePath            "/var/cache/mod_pagespeed/" must be r/w to the user that run the httpd process (apache?)
Try these changes and see what happens.

**Comment by balajikaliamoorthy** [comment] 2017-09-21 09:19
Hi Lofesa,

Thank you for the info.

I have intentionally off the module to avoid the broken pages in the PROD environment.

In PROD environment, the below files are not created (but in staging its available)
/var/cache/**mod_pagespeed/**
/var/log/**pagespeed**

We need to manually create this folder in the PROD? and need to set the owner permission.

Please let us know.

**Comment by balajikaliamoorthy** [comment] 2017-09-21 10:11
HI Lofesa,
In PROD, we have updated the permission and ownership (apache,apache).
/var/cache/mod_pagespeed/
/var/log/pagespeed
what else needs to be configured, please guide on this.

**Comment by Lofesa** [comment] 2017-09-21 12:38
Hi
First step is to make Modpagespeed work. You talk about a PROD environtment.... have a DEV one? If yes you can try if these changes make pagespeed work.... if no, enable pagespeed on PROD a see if it work.
Your config files have  default rewrite rules as CORE, these are a good set to start.
But again, firts step is make pagespeed work and not return 404 error.

when pagespeed is enabled, you can try to run www.yoursite.com/?PageSpeedFilters=+debug and look into source of the page, this parameter insert usefull debug comments into html code

P.D. Have cretated the location in the apache config?

**Comment by balajikaliamoorthy** [comment] 2017-09-21 16:57
HI Lofesa,

In DEV environment its working fine, we never faced this issue. In PROD only this issue occurred.

[pagespeed:error]  [mod_pagespeed ] Failed to delete file **/var/log/pagespeed/stats_log_global: Permission denied**

Is anything need to configure for the above error?

Working on location configuration.. Ill try the debug method and let you know.

**Comment by balajikaliamoorthy** [comment] 2017-09-22 04:56
![permission](https://user-images.githubusercontent.com/32067363/30729887-7b289f4a-9f80-11e7-95de-0689a719b4bf.png)

its permission of PROD dispathcer!

**Comment by Lofesa** [comment] 2017-09-22 08:15
apache:apache is the user that run the httpd (or apache) process? in some distros is ww-data the user.
is the same distro in DEV and PROD? are the user:group the same on both?
the 404 error on rewrited resources is gone?
to check if the issue is the user and permissions you can try to make the directories r/w for all, and see what user:group create the files then you change the directories ownership

**Comment by balajikaliamoorthy** [comment] 2017-10-24 17:20
Hi Lofesa,

We are getting the below in the error log even we disbaled the page speed module.


[Tue Oct 24 11:49:19.925513 2017] [pagespeed:error] [pid 15645:tid 140565863102208] [mod_pagespeed 1.11.33.4-0 @15645] /var/cache/mod_pagespeed/v3/10.200.201.16/http,3A/,2F10.200.201.16,3A81/health/checkpublish,.tempiNzSct:0: opening temp file: Permission denied

[Tue Oct 24 12:02:44.648812 2017] [pagespeed:info] [pid 19391:tid 140461203077248] [mod_pagespeed 1.11.33.4-0 @19391] SharedMemCache: pagespeed_default_shm/metadata_cache, sectors = 128, entries/sector = 2226,  64-byte blocks/sector = 4452, total footprint: 52445184

[Tue Oct 24 12:02:44.648878 2017] [pagespeed:info] [pid 19391:tid 140461203077248] [mod_pagespeed 1.11.33.4-0 @19391] Initializing shared memory for path: /var/cache/mod_pagespeed/ flush .

[Tue Oct 24 12:02:44.651089 2017] [mpm_worker:notice] [pid 19391:tid 140461203077248] AH00292: Apache/2.4.6 (Red Hat Enterprise Linux) Communique/4.2.0 configured -- resuming normal operations

[Tue Oct 24 12:02:44.651109 2017] [mpm_worker:info] [pid 19391:tid 140461203077248] AH00293: Server built: Jul 12 2016 05:02:54

[Tue Oct 24 12:02:44.651120 2017] [core:notice] [pid 19391:tid 140461203077248] AH00094: Command line: '/usr/sbin/httpd'

[Tue Oct 24 12:02:44.660781 2017] [pagespeed:info] [pid 19393:tid 140461203077248] [mod_pagespeed 1.11.33.4-0 @19393] Reusing shared memory for path: /var/cache/mod_pagespeed/ flush .
[Tue Oct 24 12:02:44.662707 2017] [pagespeed:info] [pid 19394:tid 140461203077248] [mod_pagespeed 1.11.33.4-0 @19394] Reusing shared memory for path: /var/cache/mod_pagespeed/ flush .

Could you please help to fix this error? 

We are using the pagespeed module, particularly for 'collapse_whitespace' filter. we are ok if we need to disable any cache filter to fix these errors.

Please advise on this.

Thanks.

**Comment by Lofesa** [comment] 2017-10-25 09:25
Ho @balajikaliamoorthy 
I think these messages are normal in restarting apache (or starting a new worker), you see the info or notice label in those messages unless the 1st.

[Tue Oct 24 11:49:19.925513 2017] [pagespeed:error] [pid 15645:tid 140565863102208] [mod_pagespeed 1.11.33.4-0 @15645] /var/cache/mod_pagespeed/v3/10.200.201.16/http,3A/,2F10.200.201.16,3A81/health/checkpublish,.tempiNzSct:0: opening temp file: Permission denied

In this case seems the file exist, but the user running httpd process had no permission to read it.

**Comment by balajikaliamoorthy** [comment] 2017-10-26 07:51
Hi Lofesa,

But we are keep getting the below error in the logs. 
[Thu Oct 26 02:46:19.804334 2017] [pagespeed:info] [pid 24459:tid 140078722500352] [mod_pagespeed 1.11.33.4-0 @24459] HTTPCache key=http://****/health/checkpublish fragment=****: **remembering recent failure for 59 seconds.**

And one final question that, how can we stop/disable pagepseed module cache?

Thanks
Balaji K

**Comment by oschaaf** [comment] 2017-10-26 08:16
The last log message you posted is informational and does not represent an error. 

To disable the module this fragment should work: 

ModPagespeedInPlaceResourceOptimization off
ModPagespeed off

**Comment by Lofesa** [comment] 2017-10-26 09:51
These directives stated by @oschaaf  disables mod_pagespeed. The module cache can´t be disabled, the cache is needed by the module to store the optimized resources. Can be a file cache or a database cache (memcached or redis) but need one, w/o it the module can´t work

**Comment by oschaaf** [comment] 2017-10-26 09:53
Ah thanks for the correction @Lofesa I indeed misread the disabling question.

**Comment by balajikaliamoorthy** [comment] 2017-10-26 18:24
Hi Lofesa  and Oschaaf,
Thank you for your support.

**Comment by oschaaf** [comment] 2017-10-27 19:59
@balajikaliamoorthy can we close this?

**Comment by oschaaf** [comment] 2017-10-30 21:52
Closing this, feel free to re-open if you experience trouble again!

**Closed as completed by oschaaf** 2017-10-30 21:52 UTC
