### ISSUE TITLE
Google mod page speed image optimization for PageSpeed Insight

### ISSUE THREAD

**Issue by oyapici** [apache/incubator-pagespeed-mod#1484] opened 2017-01-23 08:11 UTC
I have a centos linux server hosted on google compute engine running Apache. One of my domain (http://www.yeniarabafiyati.com) have image optimization issues in Google Pagespeed Insights (91% reduction): https://developers.google.com/speed/pagespeed/insights/?url=yeniarabafiyati.com&tab=desktop

I have modified following filter from default 80 to 10 that is very low,

ModPagespeedImageRecompressionQuality 10

But I still get "optimize images" message in page speed insights web site. Is there any way to reach Google Insight optimization target with Mod-PageSpeed ?

**Comment by oschaaf** [comment] 2017-01-23 10:09
It looks like yeniarabafiyati.com and www.yeniarabafiyati.com both serve
the same website, but are optimized differently.
Does that give you a hint as to what is going on?

Checking the www. version I see no complaints from Insights about images:
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.yeniarabafiyati.com%2F

Otto

**Comment by oyapici** [comment] 2017-01-23 10:57
Actually, when I check both yeniarabafiyati.com and www.yeniarabafiyati.com,  I encounter 
! Should Fix: Optimize images   message.  
Would it be possible to move optimize images to "Passed rules" ?

**Comment by oschaaf** [comment] 2017-01-23 12:04
You are right. The mobile insights for www. did not complain about images, but the desktop test still does indeed. I think the problem is that some images, for example `/images/userfiles/dis_resim8.jpg` are not resized to the width and height that they are displayed at and served too large. mod_pagespeed only cache-extends them, and does not resize them.  Even when turning on `resize_rendered_image_dimensions`. I think the involved images are injected via javascript, and as such mod_pagespeed may not be able to resize them because it does not understand this.

This also explains why these images are not converted to webp. You could try turning on browser-specific in-place optimizations for that: https://modpagespeed.com/doc/system#in_place_optimize_for_browser

**Comment by erfanimani** [comment] 2017-04-09 16:16
@oschaaf, not sure if I'm hijacking this thread, or maybe I have overlooked some settings (very likely) and apologies if that's the case.

I believe mod_pagespeed is correctly working in my case (image URL's are being rewritten and converted into webp format):

However Pagespeed Insights still manages to give me a low score:

![pagespeed-insights](https://cloud.githubusercontent.com/assets/930470/24838809/c368543e-1d81-11e7-973d-bb1b1a890d49.jpg)

I'll do a bit more research and see what I can do (however, if you have some tips/fixes without much effort on your part, please share).

Thanks

**Comment by oschaaf** [comment] 2017-04-17 15:06
Closing this issue
@erfanimani without seeing the original website and images it is hard to comment.

**Closed as completed by oschaaf** 2017-04-17 15:06 UTC
