### ISSUE TITLE
No permission to rewrite CSS

### ISSUE THREAD

**Issue by discostur** [apache/incubator-pagespeed-mod#1501] opened 2017-02-24 16:55 UTC
I'm running a fresh installation of wordpress behind a nginx reverse-proxy with mod_pagespeed. Nginx is doing the SSL termination and wordpress is running on plain http via apache.

My config looks like this:

```
pagespeed Domain https://proxy.xxx.de;
pagespeed MapOriginDomain http://91.237.xx.xx https://proxy.xxx.de;
pagespeed EnableFilters rewrite_domains;
pagespeed MapRewriteDomain https://proxy.xxx.de http://proxy.xxx.de;
```

mod_pagespeed is rewriting the URLs from http -> https and that works fine except one CSS resource:

```
[ngx_pagespeed 1.12.34.2-0] No permission to rewrite 'http://proxy.xxx.de/blog/wp-admin/css/login.min.css?ver=4.4.2'
```

If i take a look into the sourcecode you can see that pagespeed is rewriting another css resource but not the login.min.css one:

```
<link rel='stylesheet' id='dashicons-css' href='https://proxy.xxx.de/blog/wp-includes/css/dashicons.min.css?ver=4.4.2' type='text/css' media='all'/>
<link rel='stylesheet' id='login-css' href='http://proxy.xxx.de/blog/wp-admin/css/login.min.css?ver=4.4.2' type='text/css' media='all'/>
```

Is there any reason why pagespeed does rewrite the first CSS but not the second one?

Thanks
Greets
Kilian

**Comment by oschaaf** [comment] 2017-02-24 17:18
I think `pagespeed Domain https://proxy.xxx.de;` is not needed, because the `MapRewriteDomain` already implies that (see the last lines of https://modpagespeed.com/doc/domains#mapping_rewrite)

But that doesn't explain what happens. What does the original html look like, before it gets rewritten by ngx_pagespeed?

**Comment by discostur** [comment] 2017-02-27 10:04
that is the original html, without any pagespeed rewrites:

```
<link rel='stylesheet' id='dashicons-css'  href='http://proxy.xxx.de/blog/wp-includes/css/dashicons.min.css?ver=4.4.2' type='text/css' media='all' />
<link rel='stylesheet' id='login-css'  href='http://proxy.xxx.de/blog/wp-admin/css/login.min.css?ver=4.4.2' type='text/css' media='all' />
```

Just the same as after, but only with HTTP as protocol ...

**Comment by oschaaf** [comment] 2017-02-27 10:09
@discostur what version of mod_pagespeed is the website running?

**Comment by discostur** [comment] 2017-02-27 10:10
@oschaaf  ngx_pagespeed 1.12.34.2-0

**Comment by oschaaf** [comment] 2017-02-27 10:15
@discostur would it be possible to email me the full original html page plus configuration? I want to see if I can reproduce this

**Comment by discostur** [comment] 2017-02-27 10:28
@oschaaf shure, you just should have gotten mail from me

**Comment by oschaaf** [comment] 2017-03-08 15:29
@discostur this conversation went on by email for a little while, but so far I don't think there's an actual issue with ngx_pagespeed. Closing this issue, but feel free to re-open if you run into a problem with css rewriting again (or create a new issue if you run into a different problem).

**Closed as completed by oschaaf** 2017-03-08 15:29 UTC

**Comment by discostur** [comment] 2017-03-09 14:58
@oschaaf 
think you are right. we got it as far as the following:

> When I look I see most of the assets getting rewritten to https except for images in srcset attributes, and a javascript which is loaded through another javascript. I'm not sure we can do something about either of those because I think neither srcset nor javascript is parsed by the module.

Thats the problem we thought it is related to. Maybe one day pagespeed can rewrite those resources, too!

**Comment by discostur** [comment] 2017-03-09 15:37
@oschaaf 
i just found that with pagespeed 1.12.34.1 it should rewrite srcset images, too (even if the srcset tag still exists)

https://modpagespeed.com/doc/filter-image-responsive
> Before 1.12.34.1, PageSpeed would not optimize images referenced in existing srcset attributes.

But even with 
```
pagespeed Domain https://proxy.kilian-ries.de;
pagespeed MapOriginDomain http://91.237.88.116 https://proxy.kilian-ries.de;
pagespeed MapRewriteDomain https://proxy.kilian-ries.de http://proxy.kilian-ries.de;
pagespeed EnableFilters rewrite_domains;
pagespeed EnableFilters responsive_images,resize_images,responsive_images_zoom; 
pagespeed DomainRewriteHyperlinks on;

```

Pagespeed doesn't rewrite every resource on the website :/
https://proxy.kilian-ries.de

**Comment by discostur** [comment] 2017-03-09 16:43
I finally found a solution which is working for me:

http://nginx.org/en/docs/http/ngx_http_sub_module.html

Just let nginx itself rewrite everything from http -> https

```
sub_filter_types *;
sub_filter 'http://' 'https://';
sub_filter_once off;
```
