### ISSUE TITLE
SVGs not optimised

### ISSUE THREAD

**Issue by Dreamsorcerer** [apache/incubator-pagespeed-mod#1520] opened 2017-03-26 15:35 UTC
On my site at http://blog.sambull.org/ there are 3 tiny SVGs at the bottom of the page, but mod_pagespeed fails to optimise them in anyway. They are small enough that they should probably be inlined, but it's not doing this, nor is it giving performing any compression despite Pagespeed Insights warning:

    Compressing http://blog.sambull.org/…ntent/themes/penscratch-child/img/cc.svg could save 1.1KiB (50% reduction).
    Compressing http://blog.sambull.org/…ntent/themes/penscratch-child/img/sa.svg could save 655B (45% reduction).
    Compressing http://blog.sambull.org/…ntent/themes/penscratch-child/img/by.svg could save 531B (43% reduction).

**Comment by jmarantz** [comment] 2017-03-26 20:03
This is a duplicate of https://github.com/pagespeed/mod_pagespeed/issues/1231 .

**Closed as completed by jmarantz** 2017-03-26 20:03 UTC

**Comment by Dreamsorcerer** [comment] 2017-03-27 08:49
What about the inlining? Presumably, small SVGs could be inserted directly into the DOM without much fuss.

**Comment by jmarantz** [comment] 2017-03-27 11:57
I added a note about inlining to https://github.com/pagespeed/mod_pagespeed/issues/1231
