### ISSUE TITLE
Issue with Wordpress style.css

### ISSUE THREAD

**Issue by hatfieldajoshua** [apache/incubator-pagespeed-mod#1091] opened 2015-06-09 02:11 UTC
We're having some issues with Wordpress. We had an old server that ran ModPagespeed fine, however our new server is having issues with the latest stable Apache and mod_pagespeed versions.

Here's what happens:
1. ModPagespeed is disabled during development stages.
2. We then enable it prior going live.
3. For awhile the theme loads fine. The basic WordPress style.css file is rewritten within `<head>` to
4. `<style>@import url("wp-content/themes/theme-name/style.css");</style>`
5. After awhile ModPagespeed completely removes the `<style>@import url("...");</style>` line from `<head>`

This is the only file that we're having issues with and if you aren't familiar with WordPress, style.css is the primary stylesheet for a WordPress theme. All WordPress plugin stylesheets still load in just fine. However, style.css is the **only** stylesheet that gets rewritten with an `@import` and also the only one that is removed randomly after x amount of page loads (or possibly after a certain amount of time).

Example style.css:

```
/*
Theme Name:Bold Move Creative
Theme URI:http://makeaboldmove.com
Description:Theme customized for client.
Author:Bold Move Creative
Author URI:http://makeaboldmove.com
Version:1.0
Template:parent-theme
*/

@import url("../parent-theme/style.css");

body{

    color:#6b6b6b;
    font:300 16px/23px "Lato", sans-serif;
    -webkit-font-smoothing:antialiased;
    text-rendering:optimizeLegibility;
    -webkit-backface-visibility:visible;

} a{

    color:#004d96;
    outline:none;
    text-decoration:none;
    display:inline-block;
    -webkit-transition:all 0.25s ease-in;
    -moz-transition:all 0.25s ease-in;
    -o-transition:all 0.25s ease-in;
    transition:all 0.25s ease-in;

} a:hover{

    color:#00ac5c;
    text-decoration:none;

} 
/* and so on... */
```

Please help! Thanks.

**Comment by jmarantz** [comment] 2015-06-09 03:27
This is possibly a duplicate of
https://github.com/pagespeed/mod_pagespeed/issues/1050 and we hope to have
a patch soon.

**Comment by jeffkaufman** [comment] 2015-10-23 19:46
I think this is actually https://github.com/pagespeed/mod_pagespeed/issues/1092, which is now fixed.  The fix will go out in the next PageSpeed release.

**Closed as completed** 2015-10-24 14:18 UTC
