### ISSUE TITLE
Sendfile messages should not be cached

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1050] opened 2015-04-06 16:04 UTC
```
From lmaroncelli:

<link rel="stylesheet" type="text/css" 
href="www.info-alberghi.com/css/style.css">

is replaced with:

<style></style>

on:

http://www.info-alberghi.com/

which is on version: 1.9.32.2-4321



Here's the context for the missing <link>:

<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-2007570-1']);
_gaq.push(['_setDomainName', 'info-alberghi.com']);
_gaq.push(['_setAllowLinker', true]);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; 
ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 
'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; 
s.parentNode.insertBefore(ga, s);
})();

</script>
<style></style>
<script type="text/javascript" 
src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

```

Original issue reported on code.google.com by `sligocki@google.com` on 24 Feb 2015 at 4:45

**Comment by sligocki** [comment] 2015-04-20 14:56
From lmaroncelli@gmail.com:

[Tue Apr 14 10:11:38 2015] [error] [mod_pagespeed 1.9.32.3-4448 @3747] [0414/101138:ERROR:in_place_resource_recorder.cc(225)] Empty resource in IPRO for URL http://www.info-alberghi.com/js/jquery.countdown.js Response headers: HTTP/1.0 200 (null)\r\nX-Accel-Version: 0.01\r\nX-Accel-Redirect: /internal-nginx-static-location/js/jquery.countdown.js\r\nCache-Control: public, max-age=31536000\r\nExpires: Wed, 13 Apr 2016 08:11:38 GMT\r\nVary: Accept-Encoding\r\nContent-Encoding: gzip\r\nX-Powered-By: PleskLin\r\nContent-Length: 20\r\nConnection: close\r\nContent-Type: text/javascript\r\nDate: Tue, 14 Apr 2015 08:11:38 GMT\r\n\r\n Request headers: GET  HTTP/1.0\r\nHost:www.info-alberghi.com\r\nX-Real-IP: 151.47.123.28\r\nX-Forwarded-For: 151.47.123.28\r\nX-Accel-Internal: /internal-nginx-static-location\r\nConnection: close\r\nAccept: _/_\r\nUser-Agent: Mozilla/5.0 (Linux; Android 4.4.2; it-it; SAMSUNG GT-I9505 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrom
 e/28.0.1500.94 Mobile Safari/537.36\r\nReferer: http://www.info-alberghi.com/mail_scheda_inviata_new.php\r\nAccept-Encoding: gzip,deflate,sdch

**Comment by sligocki** [comment] 2015-04-20 14:57
From @jeffkaufman:

Thanks for sending this!  It looks like the key thing in this error is:

```
X-Accel-Redirect: /internal-nginx-static-location/js/jquery.countdown.js
```

Your site is set up like this, right?

```
[user] -> [nginx] -> [apache+mod_pagespeed]
```

What's happening is that apache is issuing a response like this:

   HTTP/1.0 200 (null)
   ...
   X-Accel-Redirect: /internal-nginx-static-location/js/jquery.countdown.js
   Cache-Control: public, max-age=31536000
   ...

   [empty response body]

Then nginx sees the X-Accel-Redirect header, and reads the relevant file off of disk to send out as the response body.

We can think of PageSpeed as sitting between nginx and apache, which means it sees this response before the response body is filled in.  The problem is, PageSpeed doesn't know it's seeing an incomplete response, so it saves a copy of the response body (empty) as it goes by and then later when it sees references to that file in the html it inlines it as an empty resource.

Thanks for helping us debug this!  For your site, and any other sites having this issue with 1.9.32.3 the best fix is to turn off IPRO:

```
ModPagespeedInPlaceResourceOptimization off
```

In our next release we'll make sure to handle this case.  I think what we need to do is:
- Recognize that X-Accel-Redirect means a response is incomplete, and don't cache it.
- Look for other headers that mean this and blacklist them as well.
- In case there are any other headers used for this, don't cache any responses that have an empty body. 

Relevant doc:
- http://download1.parallels.com/Plesk/Doc/en-US/online/plesk-administrator-guide/index.htm?fileName=70837.htm
- http://wiki.nginx.org/XSendfile

**Comment by sligocki** [comment] 2015-04-20 14:57
A fix is in progress.

**Comment by sachinjsk** [comment] 2015-04-20 21:17
Hi guys,

I'm running into the same issue.

I've setup enjoy-swimming.com with pretty much all the default settings. Rewrite level is set to CoreFilters. With Pagespeed on

`<link rel="stylesheet" href="http://www.enjoy-swimming.com/support-files/master.css" type="text/css" />`

was getting replaced with:

`<style></style>`

I could see that there are some css errors in that page, so I tried disabling inline_css filter, but that didn't fix it. It was generating a pagespeed specific cache file, but that was empty.

After reading comments here I tried turning off ModPagespeedInPlaceResourceOptimization, but that didn't help either.

What I find odd is that the page loads fine in Chrome but not in Firefox or Safari. You can see it in action by visiting - http://www.enjoy-swimming.com/?ModPagespeed=on

Please note that the rewritten master.css file looks good in chrome, but is empty in Safari/Firefox.

Domain: http://www.enjoy-swimming.com
Pagespeed version: 1.9.32.3-stable

Thanks for any help.

Sachin

**Comment by sligocki** [comment] 2015-04-20 22:00
Hi @sachinjsk,

Can you try flushing the mod_pagespeed cache and see if that fixes things? You can do this by simply changing the filename of `master.css` to something like `master.css?1` or by following these instructions: https://developers.google.com/speed/pagespeed/module/system#purge_cache (Leave ModPagespeedInPlaceResourceOptimization off as well)

This bug is polluting the mod_pagespeed cache and we have separate cache values for different sets of browsers. It looks like your cache has broken values for Firefox, but good values for Chrome, flushing should harmonize them.

**Comment by sachinjsk** [comment] 2015-04-20 22:13
Hi @sligocki,

I purged the entire cache via Pagespeed admin page. Still broken in Firefox/Safari.

ModPagespeedInPlaceResourceOptimization is turned off.

**Comment by sachinjsk** [comment] 2015-04-20 22:16
Please let me know if there's anything else I can help with to narrow down this bug.

**Comment by jeffkaufman** [comment] 2015-04-21 12:09
Checking enjoyswimming.com, in FF I see:

```
http://www.enjoy-swimming.com/support-files/A.master.css.pagespeed.cf.7KqI9_oL9h.css
```

which is empty, while in Chrome I see:

```
http://www.enjoy-swimming.com/support-files/A.master.css.pagespeed.cf.i2p-4h4bmP.css
```

which consists of a single @import:

```
@import url(rwd-v2.css)
```

Loading http://www.enjoy-swimming.com/support-files/rwd-v2.css , that's not empty and has lots of css directives.

**Comment by jeffkaufman** [comment] 2015-04-21 12:10
@sachinjsk Could you post your Apache config, or send it to jefftk@google.com ?

Is there anything in your Apache error log marked "error" or "warn"?

**Comment by sachinjsk** [comment] 2015-04-21 13:49
@jeffkaufman I'm trying to setup a machine with simpler out of the box apache config. Will send you the config as soon as I have them ready.

**Comment by sachinjsk** [comment] 2015-04-21 20:38
@jeffkaufman I've setup a machine with bare minimum apache config and its still broken in Safari/Firefox. I've sent you an email with the config details. There is nothing in apache error log.

Domain: http://www.enjoy-swimming.sbi2b.sitesell.com

The only change I have in pagespeed.conf:
ModPagespeedDisableFilters inline_css

**Comment by jeffkaufman** [comment] 2015-04-22 13:12
I get the same missing-css issue testing this at http://www.jefftk.com/es-include-css/index

**Comment by jeffkaufman** [comment] 2015-04-22 13:23
Somewhat reduced test case: http://www.jefftk.com/simple-include-css/index

**Comment by jeffkaufman** [comment] 2015-04-22 13:26
To get the failure:

1) Pick a unique set of irrelevant PageSpeed query options to functionally clear the metadata cache.  So `?PageSpeedFilters=+[something_silly]`.
2) Open that URL in Chrome or FF, it should work, green screen.
3) Open that URL in the other one, it shouldn't work, red screen.

On the passing side `+debug` gives me:

```
<style>@import url(support-files/rwd-v2.css) ;</style><!--Flattening failed:
A media query is too complex in http://www.jefftk.com/simple-include-css
/support-files/rwd-v2.css AND Cannot rewrite http://cfd.enjoy-swimming.
com/image-files-layout/rwd-header.png as it is on an unauthorized domain-->
```

On the failing side:

```
<style></style><!--Flattening failed: A media query is too complex in
http://www.jefftk.com/simple-include-css/support-files/rwd-v2.css-->
```

**Comment by jeffkaufman** [comment] 2015-04-22 13:37
Even simpler test case: http://www.jefftk.com/simpler-include-css/

```
$ cat index.html 
<style>body {background: red}</style>
<link rel=stylesheet href="a.css" type="text/css"/>

$ cat a.css 
@import url(b.css) ;

$ cat b.css 
﻿body {background: green}

@media screen and (min-width: 240px) {
  body {background: blue}
}
```

**Comment by sligocki** [comment] 2015-04-22 14:38
This looks like a different issue. Created a new Issue #1068, to follow this.

**Comment by sligocki** [comment] 2015-05-01 21:18
We think this will be fixed by commit 8f93d5cefcc8 which disallows us from caching empty input resources.

**Comment by crowell** [comment] 2015-05-13 19:33
reopening for follow-up cl to flush cache on upgrade.

**Comment by sligocki** [comment] 2015-05-15 21:00
Cache flushed with 6c78f97f5ac . Now this bug can be closed.

**Closed as completed by sligocki** 2015-05-15 21:00 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated

**Comment by crowell** [comment] 2015-05-15 21:06
will backport https://github.com/pagespeed/mod_pagespeed/commit/6c78f97f5ac569ea16cf936eda33abeeb5010a06 to branch 32
