### ISSUE TITLE
Not able to fetch images sending blank pages

### ISSUE THREAD

**Issue by contactmayankjain** [apache/incubator-pagespeed-mod#1108] opened 2015-07-14 03:35 UTC
Example page
http://ampletrails.com/attendance-machine

Error in apache error.log

[Tue Jul 14 08:56:04.223284 2015] [pagespeed:warn] [pid 13327:tid 140040395011840] [mod_pagespeed 1.9.32.4-7251 @13327] Waiting for completion of URL http://ampletrails.com/wp-content/themes/bizway/images/search.png for 5 sec
[Tue Jul 14 08:56:08.856891 2015] [pagespeed:warn] [pid 13327:tid 140040361441024] [mod_pagespeed 1.9.32.4-7251 @13327] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2013/02/CCE-Report-Card1-523x1024.png for 10 sec
[Tue Jul 14 08:56:09.223538 2015] [pagespeed:warn] [pid 13327:tid 140040395011840] [mod_pagespeed 1.9.32.4-7251 @13327] Waiting for completion of URL http://ampletrails.com/wp-content/themes/bizway/images/search.png for 10 sec
[Tue Jul 14 08:56:13.574533 2015] [pagespeed:warn] [pid 13327:tid 140040319477504] [mod_pagespeed 1.9.32.4-7251 @13327] Waiting for completion of URL http://ampletrails.com/wp-content/plugins/digg-digg/image/ajax-loader.gif for 5 sec
[Tue Jul 14 08:56:13.857170 2015] [pagespeed:warn] [pid 13327:tid 140040361441024] [mod_pagespeed 1.9.32.4-7251 @13327] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2013/02/CCE-Report-Card1-523x1024.png for 15.001 sec
[Tue Jul 14 08:56:14.223777 2015] [pagespeed:warn] [pid 13327:tid 140040395011840] [mod_pagespeed 1.9.32.4-7251 @13327] Waiting for completion of URL http://ampletrails.com/wp-content/themes/bizway/images/search.png for 15 sec
[Tue Jul 14 08:56:51.030840 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in https://ampletrails.com/automatic-school-students-attendance-machine/e-learning-blog
[Tue Jul 14 09:01:40.136047 2015] [pagespeed:warn] [pid 13326:tid 140040311084800] [mod_pagespeed 1.9.32.4-7251 @13326] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2012/07/ampletrails_brochure_front.gif for 5.001 sec

Files are present 

 ls -ltrh wp-content/uploads/2012/07/ampletrails_brochure_front.gif
-rw-rw-rw- 1 www-data www-data 1.3M Jan  4  2014 wp-content/uploads/2012/07/ampletrails_brochure_front.gif

**Comment by jmarantz** [comment] 2015-07-15 03:14
Duplicate of #1048

**Closed as completed by jmarantz** 2015-07-15 03:14 UTC

**Comment by jeffkaufman** [comment] 2015-07-28 15:05
@contactmayankjain are you still having this issue?  We're preparing a release with a mitigation for the bug, but because we haven't been able to reproduce it here it would be really very helpful if you could install https://github.com/pagespeed/mod_pagespeed/releases/tag/1.9.32.5 which has the draft fix, and let us know it the problem recurs.

**Comment by contactmayankjain** [comment] 2015-07-29 16:01
Can you please let me know how can I install it?

On Tue, Jul 28, 2015 at 8:35 PM, Jeff Kaufman notifications@github.com
wrote:

> @contactmayankjain https://github.com/contactmayankjain are you still
> having this issue? We're preparing a release with a mitigation for the bug,
> but because we haven't been able to reproduce it here it would be really
> very helpful if you could install
> https://github.com/pagespeed/mod_pagespeed/releases/tag/1.9.32.5 which
> has the draft fix, and let us know it the problem recurs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pagespeed/mod_pagespeed/issues/1108#issuecomment-125641133
> .

## 

Please refer us to your friends and family if you are satisfied, otherwise
let us know.

Thank You
Regards,
Mayank Jain :)
ampletrails.com
India +91 9315441078, +91 9818390836

We have specialization in Attendance Machine|Bulk SMS| Website
Development|Learning Management System|University Management System|CCTV
Cameras|RFID Cards|Library Management System|Access Control System

Disclaimer: This message contains confidential information and is intended
only for the individual named. If you are not the named addressee(s) you
should not disseminate, distribute or copy this e-mail. Please notify the
sender immediately by e-mail if you have received this e-mail by mistake
and delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secured or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission. If verification is required please request a hard-copy
version. AmpleTrails

**Comment by jeffkaufman** [comment] 2015-07-29 17:23
Are you running CentOS/RedHat or Debian/Ubuntu?  Are you running 32-bit or 64?

**Comment by contactmayankjain** [comment] 2015-07-30 02:53
Its Ubuntu 64 bit.

On Wed, Jul 29, 2015 at 10:53 PM, Jeff Kaufman notifications@github.com
wrote:

> Are you running CentOS/RedHat or Debian/Ubuntu? Are you running 32-bit or
> 64?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pagespeed/mod_pagespeed/issues/1108#issuecomment-126025883
> .

## 

Please refer us to your friends and family if you are satisfied, otherwise
let us know.

Thank You
Regards,
Mayank Jain :)
ampletrails.com
India +91 9315441078, +91 9818390836

We have specialization in Attendance Machine|Bulk SMS| Website
Development|Learning Management System|University Management System|CCTV
Cameras|RFID Cards|Library Management System|Access Control System

Disclaimer: This message contains confidential information and is intended
only for the individual named. If you are not the named addressee(s) you
should not disseminate, distribute or copy this e-mail. Please notify the
sender immediately by e-mail if you have received this e-mail by mistake
and delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secured or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission. If verification is required please request a hard-copy
version. AmpleTrails

**Comment by jeffkaufman** [comment] 2015-07-30 11:14
Release 1.9.32.6 is now out, so you should install that:

```
sudo apt-get update
sudo apt-get upgrade
sudo /etc/init.d/apache2 restart
```

**Comment by contactmayankjain** [comment] 2015-07-31 01:54
I did the update by using the commands provided by you.

Now in error.log I am seeing 

[Fri Jul 31 07:19:53.817604 2015] [pagespeed:warn] [pid 20298:tid 140455882774272] [mod_pagespeed 1.9.32.4-7251 @20298] CSS parsing error in http://ampletrails.com/attendance-machine
[Fri Jul 31 07:20:07.036418 2015] [pagespeed:warn] [pid 20298:tid 140457375889152] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2014/12/K21-Essl-Identix-Attendance-Machine.png for 5 sec
[Fri Jul 31 07:20:09.312069 2015] [pagespeed:warn] [pid 20298:tid 140457384281856] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2015/02/k-13.jpg for 5.001 sec
[Fri Jul 31 07:20:09.339918 2015] [pagespeed:warn] [pid 20298:tid 140457367496448] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2015/05/KF200-Face-Time-Attendance-System-essl-Identix.jpg for 5 sec
[Fri Jul 31 07:20:12.036715 2015] [pagespeed:warn] [pid 20298:tid 140457375889152] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2014/12/K21-Essl-Identix-Attendance-Machine.png for 10 sec
[Fri Jul 31 07:20:14.312297 2015] [pagespeed:warn] [pid 20298:tid 140457384281856] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2015/02/k-13.jpg for 10.001 sec
[Fri Jul 31 07:20:14.340205 2015] [pagespeed:warn] [pid 20298:tid 140457367496448] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2015/05/KF200-Face-Time-Attendance-System-essl-Identix.jpg for 10.001 sec
[Fri Jul 31 07:20:17.036970 2015] [pagespeed:warn] [pid 20298:tid 140457375889152] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2014/12/K21-Essl-Identix-Attendance-Machine.png for 15 sec
[Fri Jul 31 07:20:18.572916 2015] [pagespeed:warn] [pid 20298:tid 140457359103744] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2012/06/Logo_Ample_Trails_v4.png for 5 sec
[Fri Jul 31 07:20:19.312555 2015] [pagespeed:warn] [pid 20298:tid 140457384281856] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2015/02/k-13.jpg for 15.001 sec
[Fri Jul 31 07:20:19.340450 2015] [pagespeed:warn] [pid 20298:tid 140457367496448] [mod_pagespeed 1.9.32.4-7251 @20298] Waiting for completion of URL http://ampletrails.com/wp-content/uploads/2015/05/KF200-Face-Time-Attendance-System-essl-Identix.jpg for 15.001 sec

**Comment by crowell** [comment] 2015-07-31 05:35
these logs appear to be from 1.9.32.4.
@contactmayankjain it seems like you might be tracking the stable branch.

See the instructions here for changing channels

https://developers.google.com/speed/pagespeed/module/download?hl=en#how-to-change-channels

**Comment by contactmayankjain** [comment] 2016-02-07 21:46
Hello!

 

New message, please read <http://empiretoorak.com/book.php?p>

 

Mayank Jain

**Comment by contactmayankjain** [comment] 2016-02-07 21:46
Hello!

 

New message, please read <http://xerox.web.tr/changed.php?1s4r7>

 

Mayank Jain

**Comment by contactmayankjain** [comment] 2016-05-11 01:19
Hello!

You have a new message, please read http://erdallarteknik.com/peak.php?w7yl

Mayank Jain

**Comment by contactmayankjain** [comment] 2016-11-06 20:24
Hi,
Please take a look at all that  stuff  and  tell  me what you think  about it, the info is here http://rossell.delins.name/e7vby/81

Pardon my monkey thumbs, Mayank Jain
