### ISSUE TITLE
defer_js loads javascript twice

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1054] opened 2015-04-06 16:04 UTC
```
Catchpoint is reporting that defer_js is double-loading javascript files: 
http://blog.catchpoint.com/2015/03/18/pagespeed-third-party-issue/
```

Original issue reported on code.google.com by `jefftk@google.com` on 19 Mar 2015 at 4:41

**Comment by JamoCA** [comment] 2015-05-11 17:47
I encountered this while using IISpeed and was able to prevent some third party resources (jscache.com & tripadvisor.com) from being loaded twice by adding the "Disallow" directive.
https://developers.google.com/speed/pagespeed/module/restricting_urls

```
pagespeed Disallow "*jscache.com*";
pagespeed Disallow "*tripadvisor.com*";
```

We use a CMS, so it would be difficult to identify and add all third-party rules as directives to the config file.  Previously adding pagespeed_no_defer="" to scripts and resources was enough, but this seems to be ignored.  (As a result, we've disabled "defer" features altogether.)

I use the options to combine JS & CSS.  I had to disable "InPlaceResourceOptimization".  It would correctly combine original files into a single file and then additionally call the original file separately.

**Comment by Paike** [comment] 2015-11-27 18:08
On Chrome standard 45.0.2454.93 pagespeed defer is still double loading my js-file. On Firefox it only loads once.

**Comment by jeffkaufman** [comment] 2016-06-23 18:08
Testing defer_js now I see:

```
example1.js
  document.write("hello ");

example2.js
  document.write("world");

djs.html
  <script src="example1.js"></script>
  <script src="example2.js"></script>
```

When run normally I see "hello world", as expected.  When run with defer_javascript I see a blank screen.

Test it here: http://www.jefftk.com/djs?PageSpeedFilters=defer_javascript

Here are WPT runs for Chrome, FF, and Safari showing the same thing:

* Chrome: http://www.webpagetest.org/result/160623_DD_115V/
* Firefox: http://www.webpagetest.org/result/160623_0N_1163/
* Safari: http://www.webpagetest.org/result/160623_R8_1169/

**Comment by jeffkaufman** [comment] 2016-06-23 18:19
Reproduced with mps trunk.

**Comment by jeffkaufman** [comment] 2016-06-24 13:44
Moved blank js issue to #1325, since it turns out not to be related.

**Comment by jeffkaufman** [comment] 2016-06-24 14:34
Took a packet capture of chrome talking to a "frozen" copy of this (pagespeed not running, just pagespeed's output) with tcpdump.  I see:

```
c: request for html
s: html text
c: request for example1
s: example1 text
c: request for example2
c: request for js_defer
s: example2 text
s: js_defer text
c: request for example1
c: request for example2
s: example1 text
s: example2 text
c: request for example2
c: example2 text
```

(This matches what chrome reports in the network tab in developer tools.)

Note that the first requests for example1 and example2 go out before js_defer has even been requested, which suggests that labeling with `type=psajs` doesn't keep the preload scanner from fetching it.

Here's the packet capture (gzip manually disabled on the server): 
[current3.txt](https://github.com/pagespeed/mod_pagespeed/files/331892/current3.txt)

**Comment by jeffkaufman** [comment] 2016-06-24 14:37
To test this, I made a simple page with no defer javascript at all:

```
<body>
<script src="example1.js" type="text/psajs" orig_index="0"></script>
<script src="example2.js" type="text/psajs" orig_index="1"></script>
```

Loading this with chrome, example1 and example2 still gets fetched, presumably by the preload scanner since they don't get run.  [WPT agrees](http://www.webpagetest.org/result/160624_5D_QKW/1/details/).

packet capture: [current4.txt](https://github.com/pagespeed/mod_pagespeed/files/331899/current4.txt)

**Comment by jeffkaufman** [comment] 2016-06-24 14:41
My current hypothesis is that we're getting triple loads because:

1) one load from the preload scanner
2) another load from defer-js's image-based prefetch
3) another load from defer-js, for real

**Comment by jeffkaufman** [comment] 2016-06-24 14:44
To test this, I modified defer_js:

```
deferJsNs.DeferJs.prototype.attemptPrefetchOrQueue = function(url) {
//  if (this.isWebKit()) {                                                       
//    new Image().src = url;                                                     
//  }                                                                            
};
```

Now I see:

```
c: request html
s: html text
c: request example1
c: request example2
c: request js_defer
s: example1 text
s: example2 text
s: js_defer text
c: request example1
c: request example2
s: example1 text
s: example2 text
```

This is consistent with the hypothesis, since with image-based preloading available only did one load of each js file after running defer-js instead of two.

packet capture: [no-image-prefetch.txt](https://github.com/pagespeed/mod_pagespeed/files/331903/no-image-prefetch.txt)

**Comment by jeffkaufman** [comment] 2016-06-24 14:47
What's not clear to me is why Chrome would make three requests for the same url, instead of re-using what's in its cache.  Why would you want a preload scanner to throw away its results?

**Comment by jeffkaufman** [comment] 2016-06-24 14:49
I'm also not sure whether we want to thwart the preload scanner here.  The reason to thwart it is that because we're deferring the execution of the js the browser is wrong to heavily prioritize loading it since it won't actually be blocking things.  The reason not to thwart it is that simply loading the js isn't that bad, we want to preload it somehow anyway, and for page loading the important thing is keeping the incoming pipe full.

**Comment by jeffkaufman** [comment] 2016-06-24 14:53
I had thought that maybe the preload scanner results getting re-fetched was because we were using different headers, but diffing them they are both exactly:

```
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,es;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Host:www.trycontra.com
Pragma:no-cache
Referer:http://www.trycontra.com/djs-frozen.html
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
```

**Comment by jeffkaufman** [comment] 2016-06-24 16:45
I want to get a simple repro case for the preload scanner so I can talk to chromium and figure out if it's a bug, but my first try failed to trigger a duplicate load:

```
<script id=a type=invalid src=example.js></script>
<script id=b>
initial_script = document.getElementById("a");
s = document.createElement("script");
s.setAttribute("src", "example.js");
s.setAttribute("type", "text/javascript");

this_script = document.getElementById("b");
this_script.parentNode.insertBefore(s, this_script);
</script>
```

capture: [repro1.txt](https://github.com/pagespeed/mod_pagespeed/files/332111/repro1.txt)

**Comment by jeffkaufman** [comment] 2016-06-24 16:49
(@crowell just checked, and firefox doesn't see either kind of duplicate load)

**Comment by jeffkaufman** [comment] 2016-06-24 17:30
The preload scanner duplicate load doesn't happen in safari.

packet capture: [safari4.txt](https://github.com/pagespeed/mod_pagespeed/files/332188/safari4.txt)

**Comment by jeffkaufman** [comment] 2016-06-24 17:34
It looks like two things are going on:

1) Our image-based preloading doesn't work any more, and we should remove it
2) Even with (1) fixed, we have a duplicate load on Chrome (but not Safari or Firefox) where it looks like the preload scanner is ignoring what it already has when the type of the script tag is different.

We can easily fix (1) ourselves.  I've posted on net-dev@chromium to figure out if (2) is something we can get fixed in Chrome:  https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/PpITTXI7VVs

**Comment by jeffkaufman** [comment] 2016-06-24 17:46
As requested on net-dev, filed a crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=623109

**Comment by jeffkaufman** [comment] 2016-06-24 19:51
In debugging this with the Chromium folks they pointed out that these scripts should be loaded from cache, and the extra network loads only happen when you disable the cache.  The cache is disabled if you use `Ctrl+Shift+R` or if you have devtools open with `Disable Cache` checked, and I had both of these.

As long as you're running normally, without disabling the cache, this shouldn't cause any additional network loads in practice.  My guess at this point is that all the results that did show network loads were results run with `Ctrl+Shift+R`.

**Comment by jeffkaufman** [comment] 2016-06-24 19:54
We could "fix" this by using `<pagespeed-script ...>` instead of `<script type=text/psajs ...>` but I'm pretty sure this would actually be slower in practice because it thwarts the preload scanner.

**Comment by jeffkaufman** [comment] 2016-06-27 17:04
Planning to start adding `<link rel=preload>` to replace the image-based preload hack.  We don't need this yet, because currently the webkit preload scanner does find and load `<script type=text/psajs>`, but following the [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=623109) it looks like they're going to make the preload scanner stop handling these.

**Closed as completed** 2016-06-27 18:21 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
