### ISSUE TITLE
The 'Optimize Images' filter does not affect images with scandic letters

### ISSUE THREAD

**Issue by Miikat** [apache/incubator-pagespeed-mod#1190] opened 2015-11-14 22:19 UTC
The 'Optimize Images' filter does not seem to affect images which have scandic letters(ä, ö, etc) on the filename. Filter affects all the other images on my site that does not have scandic letters.

Server: Apache/2.4.10 (Debian)
X-Mod-Pagespeed: 1.9.32.10-7443

**Comment by jmarantz** [comment] 2015-11-15 01:01
Duplicate of Issue 704

**Comment by jmarantz** [comment] 2015-11-15 01:01
https://github.com/pagespeed/mod_pagespeed/issues/704

**Closed as completed by jmarantz** 2015-11-15 01:01 UTC
