### ISSUE TITLE
Redis as a caching backend

### ISSUE THREAD

**Issue by dionysio** [apache/incubator-pagespeed-mod#1143] opened 2015-09-15 23:07 UTC
Are there any plans to support redis as a caching backend?

**Comment by crowell** [comment] 2015-09-16 00:24
yes, it's already acknowledged as an accepted feature request here https://github.com/pagespeed/mod_pagespeed/wiki/Accepted-Feature-Requests 

closing as a duplicate of https://github.com/pagespeed/ngx_pagespeed/issues/777

**Closed as completed by crowell** 2015-09-16 00:24 UTC
