### ISSUE TITLE
PageSpeed image URL rewriting doesn't work with an external image lazyloader

### ISSUE THREAD

**Issue by dotstunt** [apache/incubator-pagespeed-mod#1264] opened 2016-02-12 20:22 UTC
My site images are loading fine but images from gravatar.com are not showing up. Server running on Nginx Server.

**Comment by jmarantz** [comment] 2016-02-12 20:33
Is gravatar.com running pagespeed?  It doesn't look like it.  What
specifically do you think might be attributable to a pagespeed bug?

**Comment by dotstunt** [comment] 2016-02-12 20:41
if i am setting pagespeed off, the images from gravatar are showing up but it doesn't show up while page speed is set to on.

**Comment by jmarantz** [comment] 2016-02-12 20:45
What version of PageSpeed?
What are the URLs of images not showing up?
What clients are they not showing up on?

-Josh

**Comment by dotstunt** [comment] 2016-02-12 20:52
What version of PageSpeed?
pagespeed 1.10.33.2-beta

What are the URLs of images not showing up?
`<img alt="Avatar for Ahmed Khan" title="Gravatar for Ahmed Khan" src="data:image/webp;base64,UklGRhoAAABXRUJQVlA4TA0AAAAvAAAAEAcQERGIiP4HAA==" data-lazy-src="https://secure.gravatar.com/avatar/b1323fb69ffd7246eb4da6d134d78b5f?s=80&amp;d=https%3A%2F%2Fwww.esoftload.info%2Fwp-content%2Fthemes%2Ftechblogpost%2Fimages%2Fesoftload.png&amp;r=g" srcset="https://secure.gravatar.com/avatar/b1323fb69ffd7246eb4da6d134d78b5f?s=160&amp;d=https%3A%2F%2Fwww.esoftload.info%2Fwp-content%2Fthemes%2Ftechblogpost%2Fimages%2Fesoftload.png&amp;r=g 2x" class="avatar avatar-80 photo" height="80" width="80" data-pagespeed-url-hash="4035208264" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">`

What clients are they not showing up on?
Google Chrome, IE

**Comment by jmarantz** [comment] 2016-02-12 20:58
Ah you have lazyload_images on; that's good to know.  Does anything pop up
in your Chrome Devtools Console like a JS exception, that might be
preventing the PageSpeed lazy image loader from running?

I will note that there has been a bugfix and security release you haven't
installed yet:
https://developers.google.com/speed/pagespeed/module/release_notes#release_1.10.33.4-beta
and that this release fixes an image display problem on Chrome on iOS that
appeared recently that browser actually lost the ability to display webp in
a recent update.

However, I was not aware of a problem on IE, so that leads me to suspect
the problem is with the lazyload javascript.

Does everything work fine if you turn off lazyload_images (as an
experiment)?

-Josh

**Comment by jmarantz** [comment] 2016-02-12 21:44
Sorry, I didn't look closely enough.  You are using some non-pagespeed lazyload_images solution.  I saw "data-lazy-src" in the URL you pasted, but the syntax for PageSpeed is data-pagespeed-lazy-src.

This must be a case of where PageSpeed and your existing lazy-loader are getting in each others way.  I'm not quite sure of exactly what the symptom is, but you could try either:
1. turning off your existing lazyloader and using PageSpeed's instead.  The advantage of this is that it will work properly with PageSpeed's existing image optimization, inlining, and criticality analysis.  PageSpeed computes which images are critical, so it can inline the critical ones if they are small enough, and lazyload only the non-critical ones.
2. telling pagespeed to preserve image URLs.  You are using nginx so the conf file syntax is:
   pagespeed ImagePreserveURLs on;
   This will disable image URL rewriting, sizing to context, inlining, and advanced features of webp.  But it will still recompress images and will allow you to run your existing lazyloader.

My preference is #1, of course, but there may be something special about your existing image lazyloader.

**Comment by dotstunt** [comment] 2016-02-12 21:58
I too preferred #1 and it worked by disabling the external lazyloader. Thanks!! 

Release 1.10.32.4-beta is being mentioned instead of Release 1.10.33.4-beta in the link.
https://developers.google.com/speed/pagespeed/module/release_notes#release_1.10.33.4-beta

**Comment by jmarantz** [comment] 2016-02-12 22:44
Glad you got it working.  will pagespeed get re-enabled on gravatar.com soon?  Or are you just experimenting?

Thanks for the heads-up on the doc typo; this will be fixed next week.

Closing this bug for now; please re-open if I missed something.

**Closed as completed by jmarantz** 2016-02-12 22:44 UTC
