### ISSUE TITLE
Suggestion to finally fix mod_ruid2 permissions issue

### ISSUE THREAD

**Issue by ernexus** [apache/incubator-pagespeed-mod#1323] opened 2016-06-22 20:59 UTC
Hi, time have passed but still no support for mod_ruid2? 

We managed to separate pagespeed cache folders for every user in Directadmin with VirtualHosts. But the problem still exists. Files and folders still sometimes have wrong ownership. Even if we force new folders and files to have 777 with ACL the files still have 600 (new folders have 777) and if the owner is different it does not work right. For example: !clean!time! can't be read properly and etc.

**Suggestion:**
Can we have additional variable just like "ModPagespeedFileCachePath" (with it we can seperate cache folders for every user) but for default owner names? All we have to do is check if  "ModPagespeedInheritVHostConfig" is "on" and our new field is not empty: "ModPagespeedFileCacheOwner" have specific username for the ownership. It could be possible solution for us and may others.

I am not very experienced with pagespeed source code and can't provide with actual code. But i think i found possible code location for implementing such a thing. File: pagespeed\apache\mod_instaweb.cc in the function "give_dir_apache_user_permissions". There is a code:
`if (chown(path.c_str(), unixd_config.user_id,
            unixd_config.group_id) != 0) {
    factory->message_handler()->Message(
        kError, "Unable to set proper ownership of %s (%s)",
        path.c_str(), strerror(errno));
    return false;
  }`

If we could replace "unixd_config.user_id" and "unixd_config.group_id" with the variable from config, i believe it may work. If someone willing to make new pull with the solution we would be really grateful.

Thanks.

**Comment by jmarantz** [comment] 2016-06-22 21:46
If only bugs got fixed automatically due to the passage of time :)

It probably would help us prioritize this if we had more votes on one bug, rather than adding another bug related to this.  There are several open on  mod_ruid2 :

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+ruid2++pagespeed

I recall that there are potential workarounds:
1. Having a separate FileCachePath per vhost -- I'm not sure if that would work or not.
2. Using memcached instead of the FileCache

I'm not sure I totally understand how the extra config would help.  I think the chown will fail if MPS runs as a normal user that doesn't own the existing cache files.

Another solution, which is not possible today but should be in the next major revision, is to delegate cache read/write to shared process, which each subprocess communicate with via RCP.  That's basically the same class of solution as memcached, which should be trivial to implement and work today.

**Comment by ernexus** [comment] 2016-06-22 22:11
We are already using the first workaround and we still have problems. It's not a 100% solution because it still causes the permission problems.

Does not apache owns the files? I believe it only chown later for specific Directadmin user.

Another solutions i could think of:
1. To write files with 644 permission instead of 600. We managed to force new folders created with 777.
2. Don't force assign ownership and let system settings like ACL to assign it.

**Comment by jmarantz** [comment] 2016-06-22 23:15
Honestly I don't know that much about mod_ruid2, and I don't know exactly what situation the first workaround doesn't cover without seeing a lot more detail.  In fact given the workaround suggested, I do not understand why writing files with 644 permissions would help.

What about the second workaround: using memcached?

**Comment by ernexus** [comment] 2016-06-22 23:49
The first workaround almost got it, as there are only read issues. For example: !clean!time! can't be read properly and it flushes "just to be safe". It repeats the flush procedure way too often, reducing web load times. If we manually give it 644 or 777 it can be read, but later this file will be recreated again with 600 after flush.

We can't spare any ram for pagespeed additionally, there is varnish and other software already installed.

Thanks for responses :)

**Comment by jmarantz** [comment] 2016-06-23 00:04
Actually that's pretty helpful.  If the problem is just that !clean!time
file that is written to help us time cache GC that probably can be fixed.

**Comment by ernexus** [comment] 2016-06-23 00:32
We are getting those errors very often (sometimes even few seconds apart for same users):
`Failed to read cache clean timestamp /home/user/tmp/mod_pagespeed/!clean!time!.  Doing an extra cache clean to be safe.`

We do not get any other major errors, some "Fetch timed out" from time to time. My guess it could be due the overload of cache cleans.

**Comment by jeffkaufman** [comment] 2016-06-27 18:57
Let's move discussion on this to https://github.com/pagespeed/mod_pagespeed/issues/635 to keep it all in one place.  Closing here; followup there.

**Closed as completed by jeffkaufman** 2016-06-27 18:57 UTC
