### ISSUE TITLE
element :lang is compressed to element:lang which has different meaning

### ISSUE THREAD

**Issue by yukuku** [apache/incubator-pagespeed-mod#1096] opened 2015-06-19 04:32 UTC
For example I have in the original CSS:

```
.en :lang(in)
```

(means: elements that has lang="in" as children of any element that has class="en")

After compression, it becomes:

```
.en:lang(in)
```

(without the space, which means elements that has both class="en" and lang="in")

This breaks sites like http://www.bibleforandroid.com, specifically 
http://www.bibleforandroid.com/css/umum.css

**Comment by jmaessen** [comment] 2015-06-19 19:08
I'm having trouble reproducing this on my machine.  What version of pagespeed are you using?  I'm seeing the last few rules in the above css minified as follows:

.in :lang(en) {display:none}.in>.navbar>.container>.navbar-collapse>.translator>.indb{color:#03a9f4!important}.en>.navbar>.container>.navbar-collapse>.translator>.engb{color:#03a9f4!important}.in>.navbar>.container>.navbar-header>.translator2>.indb{color:#03a9f4!important}.en>.navbar>.container>.navbar-header>.translator2>.engb{color:#03a9f4!important}.en :lang(in) {display:none}.translator{float:right}.translator-button{margin-top:12px;font-size:14px;color:#888;background:none;border:none}.translator-button:hover{color:#03a9f4}@media (min-width:767px){.translator2{display:none}}

So the spaces are being preserved.

**Comment by yukuku** [comment] 2015-06-20 04:07
I noticed this when using Chrome Compression Proxy (Data saver in chrome mobile).

When I look up at the page about that, it says it uses pagespeed, so I guess it's the same as this.

The response header contains Via: 1.1 Chrome-Compression-Proxy

**Comment by jmarantz** [comment] 2015-06-22 02:13
Can you enter this as a Chrome bug?  It's best to track the bug in Chrome since that's how you reproduced it.  Please reference the chromium bug number in this bug, and vice versa.

 https://code.google.com/p/chromium/issues/entry?
template=Defect%20on%20Mac%20OS&comment=Chrome+Version+++++++%3A+43.0.2357.124%0AOS+Version%3A+OS+X+10.10.3%0AURLs+%28if+applicable%29+%3A%0AOther+browsers+tested%3A%0A++Add+OK+or+FAIL+after+other+browsers+where+you+have+tested+this+issue%3A%0A+++++Safari+5%3A%0A++Firefox+4.x%3A%0A+++++IE+7%2F8%2F9%3A%0A%0AWhat+steps+will+reproduce+the+problem%3F%0A1.%0A2.%0A3.%0A%0AWhat+is+the+expected+result%3F%0A%0A%0AWhat+happens+instead+of+that%3F%0A%0A%0APlease+provide+any+additional+information+below.+Attach+a+screenshot+if%0Apossible.%0A%0AUserAgentString%3A+Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_10_3%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F43.0.2357.124+Safari%2F537.36%0A%0A

**Comment by yukuku** [comment] 2015-06-22 02:25
Filed at
https://code.google.com/p/chromium/issues/detail?id=502880

**Comment by jmarantz** [comment] 2015-06-22 19:28
I'm going to close this issue: I verified that http://www.bibleforandroid.com/css/umum.css does not have that minification bug in mod_pagespeed, and we are looking at how to fix it in the Data Reduction Proxy; follow along the Chrome bug for that.

**Closed as completed by jmarantz** 2015-06-22 19:28 UTC
