### ISSUE TITLE
deadline_exceeded and Uncacheable content, preventing rewriting. Cloudfront

### ISSUE THREAD

**Issue by vladnaiden** [apache/incubator-pagespeed-mod#1498] opened 2017-02-20 20:16 UTC
For a long period of time I was trying to fix issues with setting pagespeed for cloudfront, already have read a lot of threads with same errors and still can't make some filters to work properly. I have 3 separate websites and only with only one of them where I'm using cloudfront have these problems

I'm using nginx with pagespeed v. 1.11.33.0-0 + cloudfront as CDN

I have disabled some filters because not sure that I really need them, they are set by pagespeed by default but both with or without them still getting same errors

Would really appreciate to help me somebody with these issues)))
Here my pagespeed settings:

# Google PageSpeed
    pagespeed on;
    pagespeed Domain https://example.com;

    pagespeed FetchHttps enable,allow_self_signed,allow_unknown_certificate_authority,allow_certificate_not_yet_valid;

    pagespeed MapRewriteDomain "https://1241asdas.cloudfront.net" "https://example.com";
  
    pagespeed RewriteLevel PassThrough;

    #pagespeed AllowVaryOn auto;
    #pagespeed RespectVary on;

    pagespeed UseExperimentalJsMinifier on;
    pagespeed Disallow */amp/*;

    pagespeed EnableFilters convert_png_to_jpeg;
    pagespeed EnableFilters remove_comments;
    pagespeed EnableFilters collapse_whitespace;
    pagespeed EnableFilters make_google_analytics_async;
    pagespeed EnableFilters rewrite_css,sprite_images;
    pagespeed EnableFilters responsive_images,resize_images;
    pagespeed EnableFilters lazyload_images;
    pagespeed EnableFilters insert_image_dimensions;
    pagespeed EnableFilters resize_rendered_image_dimensions;
    pagespeed EnableFilters convert_jpeg_to_progressive;
    pagespeed EnableFilters elide_attributes;     
    pagespeed EnableFilters convert_meta_tags;
    pagespeed EnableFilters elide_attributes;
    pagespeed EnableFilters inline_images;
    pagespeed EnableFilters insert_dns_prefetch;

    pagespeed DisableFilters add_head;
    pagespeed DisableFilters combine_css;
    pagespeed DisableFilters combine_javascript;

    pagespeed FileCachePath "/var/tmp/cache/ngx_pagespeed/";
    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
      add_header "" "";
    }

    location ~ "^/pagespeed_static/" { }
    location ~ "^/ngx_pagespeed_beacon$" { }

# Google PageSpeed

**Comment by oschaaf** [comment] 2017-02-20 20:46
Could you tell us about the errors that are you seeing? Do they also occur when you take CloudFront out of the equation?

**Comment by vladnaiden** [comment] 2017-02-20 23:27
@oschaaf , thanks for your prompt response)))
Found errors deadline_exceeded and Uncacheable content when was checking the website with curl I used javascript_inline filter but it did not work same errors appear on some images. Same settings set for two  another websites but without cloudfront and everything works great)) Also receiving an error Serf internal error 20014 when using pagespeed settings for sertificates and actually most of filters work on static.example.com version, but not on example.com. And sometimes javascript_inline worked too but only on static.example.com)))) I have read your recommendations about pagespeed  that it may process page and better check website 5 min later or after 4-5 reload but it did not inline script properly in the end))) I really want to understand what I am doing wrong but already ran out of guesses what it could be)))

**Comment by oschaaf** [comment] 2017-02-21 09:06
The `deadline exceeded` messages should be transient and are safe to ignore. 

On messages about uncacheable content: If PageSpeed sees cache-control headers such as nocache or private it will not rewrite the resources. To fix that you can either modify the configuration to serve the involved resources as cacheable, or set up pagespeed to directly load files from disk: https://modpagespeed.com/doc/https_support#load_from_file

**Comment by vladnaiden** [comment] 2017-02-21 13:45
@oschaaf, I am not sure about loading files directly, I read the thread where you advised to use pagespeed Domain example.com to avoid direct load and I thought it could help but not really)) I used loadfrom file before and it did not work either. I thought pagespeed modify files by itself with headers public cache and I could just disable that setting. Just in case I already have added code in server block         
location ~* \.(gif|jpg|png|js|css|svg|woff)$ {
            add_header Cache-Control "public, max-age=31536000";
            expires 30d;
        } 

You were right, deadline exceeded and uncacheable content disappeared but still javascript_inline not working. Oh, I see it looks like after my setting changed I should wait more than 5 minutes, because now I see when checking the website with curl that on s.example.com version pagespeed is turned on and javascript inlined in html and on example.com cannot find any pagespeed mod or filters using.

Just added loadfrom file s.example.com. Is there anything more I could add in settings? Sorry for asking you, it just to see real result it seems like I will have to wait for couple of hours or even more to understand that everything is work properly)))

**Comment by oschaaf** [comment] 2017-02-21 20:31
You may have to test with a real browser instead of curl, because some of the optimizations will not show up when you test only with curl. 
Also you should not have to wait for hours to see results, a couple of page reloads in a browser and you should be OK.

**Comment by vladnaiden** [comment] 2017-02-21 23:10
@oschaaf, yeah, I thought that too))) But when I wrote about the issue I checked the website that was already build and online for at least 2-3 hours)) Also of course I am testing website with browser, curl mostly show me errors that I could not see in console of browser, I do not really know what shall I do more to resolve this problem could you help me with that?))) I could send you link( not sure that I could place it in public thread ) or would be really grateful for any advice I could receive from you, and I really do not understand my settings should work, right? What could cause the problem?

**Comment by oschaaf** [comment] 2017-02-21 23:14
If you PM me a link, I'll have a look.

**Comment by abieri** [comment] 2017-02-23 08:26
@oschaaf I'm having exact same issue using cloudfront. Can I pm you a link with my mps configuration?

**Comment by oschaaf** [comment] 2017-02-23 11:33
@abieri See https://github.com/pagespeed/mod_pagespeed/issues/1498#issuecomment-281284675

Also, in @vladnaiden's case, CF is also caching html responses from the origin (which is the mod_pagespeed-enabled webserver). 

For mod_pagespeed to work as designed, html should not be cached by the CDN, unless you are able to set up the downstream caching feature (which I think you can't).

**Comment by vladnaiden** [comment] 2017-02-23 17:32
After few days of research, I have made cloudfront  to work with pagespeed.
 Thanks @oschaaf for his advises and fast responses, in admin panel I have found an errors that downstream caching feature could resolve, maybe I'll use it later, but it's just working great how it is for now)))
Found an answer in this article https://romain.dorgueil.net/blog/en/web-performance/2016/09/06/3-amazon-cloudfront-cdn.html
Commented with # settings that not really worked for me
To tell the truth not really got how did it work to the end, because before with same settings my scripts were not inlined, but I really needed to)))


Pagepseed conf:
    pagespeed on;

example.com = CNAMe cloudfront
s.example.com = origin cloudfront
asdo171da719.cloudfront.net = domain cloudfront

    #pagespeed Domain https://example.com;
    pagespeed Domain https://s.example.com;
    #pagespeed LoadFromFileMatch "^https?://s.example.com/" "/var/www/example";
    #pagespeed LoadFromFileRuleMatch disallow .*;
    #pagespeed LoadFromFileRuleMatch allow \.css$;
    #pagespeed LoadFromFileRuleMatch allow \.jpe?g$;
    #pagespeed LoadFromFileRuleMatch allow \.png$;
    #pagespeed LoadFromFileRuleMatch allow \.gif$;
    #pagespeed LoadFromFileRuleMatch allow \.js$;
    pagespeed PreserveUrlRelativity on;

    pagespeed SslCertDirectory /etc/letsencrypt/live/s.example.com/;
    pagespeed SslCertFile fullchain.pem;
    pagespeed FetchHttps enable,allow_self_signed,allow_unknown_certificate_authority,allow_certificate_not_yet_valid;

    pagespeed EnableFilters rewrite_domains;
    #not working
    #pagespeed MapOriginDomain "https://example.com" "https://s.example.com";
    #pagespeed MapRewriteDomain "https://s.example.com" "https://example.com";

    pagespeed MapRewriteDomain "https://asdo171da719.cloudfront.net" "https://s.example.com";
  
    pagespeed RewriteLevel PassThrough;

    pagespeed AllowVaryOn auto;
    pagespeed RespectVary on;

    pagespeed UseExperimentalJsMinifier on;
    pagespeed Disallow */amp/*;

    pagespeed EnableFilters convert_png_to_jpeg;
    pagespeed EnableFilters remove_comments;
    pagespeed EnableFilters collapse_whitespace;
    pagespeed EnableFilters make_google_analytics_async;
    pagespeed EnableFilters rewrite_css,sprite_images;
    pagespeed EnableFilters responsive_images,resize_images;
    pagespeed EnableFilters lazyload_images;
    pagespeed EnableFilters insert_image_dimensions;
    pagespeed EnableFilters resize_rendered_image_dimensions;
    pagespeed EnableFilters convert_jpeg_to_progressive;
    pagespeed EnableFilters elide_attributes;     
    pagespeed EnableFilters convert_meta_tags;
    pagespeed EnableFilters elide_attributes;
    pagespeed EnableFilters inline_images;
    pagespeed EnableFilters insert_dns_prefetch;

    #always disable
    pagespeed DisableFilters add_head;
    pagespeed DisableFilters combine_css;
    pagespeed DisableFilters combine_javascript;


pagespeed FileCacheSizeKb          102400000;
pagespeed FileCacheCleanIntervalMs 3600000;
pagespeed FileCacheInodeLimit      5000000;


pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;


pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;



    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
      add_header "" "";
    }

location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }




location /ngx_pagespeed_statistics { allow 123.12312.123123; deny all; }
location /ngx_pagespeed_global_statistics { allow 123.12312.123123 ; deny all; }
location /ngx_pagespeed_message { allow 123.12312.123123 ; deny all; }
location /pagespeed_console { allow 123.12312.123123 ; deny all; }
location ~ ^/pagespeed_admin { allow 123.12312.123123; deny all; }
location ~ ^/pagespeed_global_admin { allow 123.12312.123123; deny all; }





Also nginx config:
Put it after http 
pagespeed ForceCaching on;
pagespeed MessageBufferSize 100000;
pagespeed GlobalStatisticsPath /ngx_pagespeed_global_statistics;
pagespeed GlobalAdminPath /pagespeed_global_admin;
pagespeed UsePerVhostStatistics on;
pagespeed FileCachePath "/var/tmp/cache/ngx_pagespeed/"; <--- not sure about that

            add_header Access-Control-Allow-Origin "https://s.example.com";
            add_header Access-Control-Allow-Origin "https://example.com";  <--- wild card doesn't really worked for me, maybe it does now but I would just leave it how it is for now))))

        location ~* \.(gif|jpg|png|js|css|svg|woff)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=360000";
        }

        location / {
            proxy_cache_bypass  $http_cache_control;
        }

Not sure that it totally worked with all filters, my javascripts and a lot of other filterssare working so I'm glad))

**Comment by oschaaf** [comment] 2017-02-23 17:41
Great to hear it's working. Closing this issue.

**Closed as completed by oschaaf** 2017-02-23 17:41 UTC

**Comment by abieri** [comment] 2017-02-24 01:07
@oschaaf my cache policy is set to public https://d18md549cxuah8.cloudfront.net/images/search_page/1487612520086-0.jpeg/280/200

therefore i can't use the loadfrom file closure as this is a resized image on the fly. Could that be the issue?

**Comment by oschaaf** [comment] 2017-02-24 07:20
@abieri Yes, `LoadFromFile` only works for static files

**Comment by abieri** [comment] 2017-02-27 01:15
@oschaaf Still my resource has cache policy set to public, is there any other potential issue that'd prevent the rewriting of the image?

https://d18md549cxuah8.cloudfront.net/images/search_page/1487612520086-0.jpeg/280/200

**Comment by oschaaf** [comment] 2017-02-27 09:00
@abieri that image is served with: `Cache-Control:public, max-age=0`
Can you bump `max-age` to a positive value?

**Comment by abieri** [comment] 2017-02-27 10:33
@oschaaf brilliant, that made the trick. Cloudfront was overriding my max-age values
